### ISSUE TITLE
Could not create output file, error code=0x80070005

### ISSUE THREAD

**Issue by 3F** [3F/DllExport#1]
Failed when is used signed assembly by .snk or .pfx key

```
DllExport.targets(58,5): error : Assembling 'C:\Users\reg\AppData\Local\Temp\tmp88A8\Gateway.il'  to DLL --> 'D:\prg\qsin\bin\Debug\Gateway.dll'
DllExport.targets(58,5): error : Source file is UNICODE
DllExport.targets(58,5): error : 
DllExport.targets(58,5): error : Assembled method Gateway.Connector::entrypoint
DllExport.targets(58,5): error : Assembled method Gateway.Connector::onProc
DllExport.targets(58,5): error : Assembled method Gateway.Lua::.ctor
DllExport.targets(58,5): error : Creating PE file
DllExport.targets(58,5): error : Could not create output file, error code=0x80070005
DllExport.targets(58,5): error : 
DllExport.targets(58,5): error : ***** FAILURE ***** 
```

Same for original tool (v1.2.7)... hmm

**Comment by 3F** [comment]
the IL code seems normal, i.e.:

* I don't see any references of dllexport (`.assembly extern` ... etc.)
* and mainly:

```
.corflags 0x0000000b  ->  .corflags 0x00000002 //x86
```

```csharp
.method public hidebysig static int32 
        modopt(['mscorlib']'System.Runtime.CompilerServices.CallConvCdecl')  
        'entrypoint'(native int 'L')
{
    .export [1] as 'Init'
    
    //...
}
```

**Comment by 3F** [comment]
hmm, 0x80070005 was access denied :) nice

TODO:
* describe this error for user https://support.microsoft.com/en-us/kb/816731
* and try to get rights automatically

*anyway, works.*

**Comment by ChahatKumar** [comment]
@3F Hey i am getting the same error 

```
Assembled method Microsoft.ApplicationInsights.Channel.Transmission::CreateRequest
Assembled method Microsoft.ApplicationInsights.Channel.Transmission::.cctor
Assembled method Microsoft.ApplicationInsights.Channel.TransmissionStatusEventArgs::.ctor
Assembled method Microsoft.ApplicationInsights.Channel.TransmissionStatusEventArgs::.ctor
Assembled method Microsoft.ApplicationInsights.Channel.TransmissionStatusEventArgs::get_Response
Assembled method Microsoft.ApplicationInsights.Channel.TransmissionStatusEventArgs::get_ResponseDurationInMs
Assembled method <PrivateImplementationDetails>::ComputeStringHash
Creating PE file
Could not create output file, error code=0x80070005

***** FAILURE *****
```


Was getting a few syntax errors for some function which I didn't need so removed them ,
I am basically trying to change the name of dll for Microsoft.ApplicationInsights.

De assembled and reassembling gives this errors

any insights please?

**Comment by 3F** [comment]
@ChahatKumar What version?

**Comment by ChahatKumar** [comment]
@3F Microsoft. Application Insights. 2.17.0

This was last stable release

**Comment by 3F** [comment]
@ChahatKumar No :) What version of the *DllExport* package are you using here?

**Comment by ChahatKumar** [comment]
Hi @3F  , apologies that i got confused.
I actually used these commands :
`ildasm /all /out=ICSharpCode.SharpZipLib.il ICSharpCode.SharpZipLib.dll
ilasm /dll /out=shortname.dll ICSharpCode.SharpZipLib.il`

And had the same error .
Sorry for confusion!

**Comment by 3F** [comment]
@ChahatKumar For the current case you need elevate permissions/rights in the used environment.

You can automate this through our tool and its *Pre-processing* etc. Read the documentation.

**Comment by ChahatKumar** [comment]
@3F oh okay! Thanks! :D
