### ISSUE TITLE
MyExportedFunction(char* dst)

### ISSUE THREAD

**Issue by olluz** [3F/DllExport#105]
My function call MyExportedFunction gets passed a char* and is expected to fill it with a string. How can I DllExport this ?

Thanks in advance (and sorry this is not a bug)

I am trying this:

`[DllExport("MyExportedFunction", CallingConvention = CallingConvention.Cdecl)]
        public static void MyExportedFunction(out IntPtr str)
        {
            str = (IntPtr) Marshal.StringTo....("SomeString");
        }`

but it is not working as expected.

**Comment by 3F** [comment]
> but it is not working as expected.

the most ever detailed issue. Such as ... ?

* [To check/control/list of export](https://github.com/3F/DllExport/wiki/Export)
* [Examples](https://github.com/3F/DllExport/wiki/Examples) + screencasts

Here's complete workable example (C++/C#/VB.NET): 
https://github.com/3F/Examples/tree/master/DllExport/BasicExport

**Comment by berbun** [comment]
@olluz You simply want to write a string at the address of the pointer (`char*`/`IntPtr`)?
You could use Marshal or Buffer or UnmanagedMemoryStream or StringBuilder, or, unsafe context... Whatever fits your needs, it also depends whether you have access to the native function, there are many ways really. If you're working with `IntPtr`, convert your string into an array of bytes and write those bytes into the pointer.
You should read some P/Invoke (Platform Invoke) tutorials too.
But, this has nothing to do with DllExport.

**Comment by olluz** [comment]
Thank you both for taking the time to answer my question. And sorry for not being more precise. 
You are right, this has nothing to do with DllExport. It is not a bug. I was more hoping to get some help on how to solve my problem.
I will try to explain in more detail.

I have an EXE and DLL (in C++) that work perfectly together.

EXE:
`BOOL CheckDLL(void)`
`{`
`	char str[80];`
`	char str1[] = "Version";`
`	GetVersion(str);`
`	if(strcmp(str, str1) != 0)`
`	{		`
`		return FALSE;`
`	}`
`	return TRUE;`
`}`

DLL:
`void WINAPI GetVersion(char* dst)`
`{`
`	if(dst) strcpy(dst, "Version");`
`}`

Now, I am trying to replace DLL using your DLLExport.

C# DLL:
`[DllExport("GetVersion", CallingConvention = CallingConvention.Cdecl)]`
`public static void GetVersion([MarshalAs(UnmanagedType.LPStr)] out StringBuilder sb)`
`{`
`    sb = new StringBuilder("Version");`
`}`

But the EXE will only receive some hieroglyphs.

Can you please give me a hint or code example on how to achieve this ?

Thanks in advance and sorry for misusing your "Issues" section with my question

**Comment by 3F** [comment]
@olluz, 

As @berbun mentioned, you can achieve this by lot of ways. 
I prefer and recommend IntPtr: here's related [example](https://github.com/3F/DllExport/wiki/Examples-Part-2) with [screencast](https://www.youtube.com/watch?v=QXMj9-8XJnY).
