### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by berbun** [3F/DllExport#106]
I get an error while trying to build a project which has DllExport package (version 1.6.3):
> The process cannot access the file because it is being used by another process.

Error window says the following: at \packages\DllExport.1.6.3\tools\net.r_eg.DllExport.targets (line 59 column 5)

---

This issue have started happening after I upgraded the DllExport reference to a newer [version 1.6.3.29130 - f61ffe9](https://github.com/3F/DllExport/releases/tag/v1.6.3).
I have tried building with VS2017 (version 15.9.13) and VS2019 (version 16.1.5), both have the same compile-time error (sometimes, I would kill MSBuild process, and then it would rebuild successfully, but now even that is not helping anymore). I can't build my project anymore, the only workaround I could do is revert back to using older DllExport version. So, I reinstalled DllExport but installed [version 1.6.2](https://github.com/3F/DllExport/releases/tag/v1.6.2), and now it all works just fine again.
So, it means this bug has been introduced very recently (in version 1.6.3). Please fix it.
This is a blocking issue, I am stuck at version 1.6.2 and cannot upgrade due of the "file-being-already-opened" bug.

---

Here is the stack trace from the Output window:
```
\packages\DllExport.1.6.3\tools\net.r_eg.DllExport.targets(59,5): error : The process cannot access the file because it is being used by another process.
1>     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>     at System.IO.__Error.WinIOError()
1>     at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
1>     at RGiesecke.DllExport.Parsing.IlAsm.Run(String outputFile, String ilSuffix, CpuPlatform cpu) in C:\projects\dllexport\RGiesecke.DllExport\Parsing\ILAsm.cs:line 106
1>     at RGiesecke.DllExport.Parsing.IlAsm.ReassembleFile(String outputFile, String ilSuffix, CpuPlatform cpu) in C:\projects\dllexport\RGiesecke.DllExport\Parsing\ILAsm.cs:line 52
1>     at RGiesecke.DllExport.DllExportWeaver.reassembleFile(IlAsm ilAsm, String outputFile, String ilSuffix, CpuPlatform cpu) in C:\projects\dllexport\RGiesecke.DllExport\DllExportWeaver.cs:line 198
1>     at RGiesecke.DllExport.DllExportWeaver.RunIlAsm(IlAsm ilAsm) in C:\projects\dllexport\RGiesecke.DllExport\DllExportWeaver.cs:line 149
1>     at RGiesecke.DllExport.DllExportWeaver.Run() in C:\projects\dllexport\RGiesecke.DllExport\DllExportWeaver.cs:line 89
1>     at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.Execute() in C:\projects\dllexport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 463 (TaskId:39)
1>Done executing task "DllExportAppDomainIsolatedTask" -- FAILED. (TaskId:39)
1>Done building target "DllExportMod" in project "DllExportTest.csproj" -- FAILED.: (TargetId:69)
```

**Comment by 3F** [comment]
Thanks for the report!

I'll try to reproduce your problem ASAP. And seems like it does not related to #73

> it means this bug has been introduced very recently (in version 1.6.3)

My first guess about 1.6.3 it's upgrading Cecil to 0.10.3. Because they already changed internal behavior with AssemblyDefinition: https://github.com/3F/DllExport/pull/97#issuecomment-496319449

There is something that I missed o_O But anyway, here's an disposing for 0.10.x (0.9.x does not use IDisposable at all) :

https://github.com/3F/DllExport/blob/9833bc78b0f514441edd8afd59a8d4f9aee458c9/NSBin/Rmod.cs#L120-L122

Other changes shouldn't affect for IlAsm.ReassembleFile, hmm.

Does it affect also for any new projects from scratch? or only for some specific?

**Comment by berbun** [comment]
> Does it affect also for any new projects from scratch?

All projects (new and old, whichever uses the new version 1.6.3), I have tried it out on a fresh new class library project, just before reporting it here on GitHub, and it produced the same error.
I think so, MSBuild and some external process started by DllExport task is trying to rewrite an already opened file. Making it completely block the compiler process once unhandled exception is thrown.
IMO, error handling should be improved upon, especially around file I/O operations.

**Comment by 3F** [comment]
> All projects (new and old, whichever uses the new version 1.6.3)

Thanks for the new details.

>  Making it completely block the compiler process once unhandled exception is thrown.

Is it happening beyond the timeout for injection (30000ms by default from manager) ?

**Comment by 3F** [comment]
@berbun Please check this out: https://github.com/3F/DllExport/releases/tag/CI-build-115

**Comment by berbun** [comment]
> Please check this out: https://github.com/3F/DllExport/releases/tag/CI-build-115

I have tried out CI-build-115, and it is not fixing the issue.

**Comment by 3F** [comment]
@berbun Just to be sure, can you put information here about tested build version:

```
DllExport -build-info
```

**Comment by berbun** [comment]
I don't know, what am I supposed to download from the assets, because I downloaded [this file](https://github.com/3F/DllExport/releases/download/CI-build-115/DllExport.bat)...
And here is the output:
```
    S_NUM:              1.6.3
    S_REV:              29130
    S_NUM_REV:          1.6.3.29130
    S_REL:
    bSha1:              f61ffe9
    bName:              master
    bRevc:              134
    Wizard .NET:        v4.0
    Configuration:      PublicRelease
    Platform:           AnyCPU
    cfgname:            Release
    revDeltaBase:       2016/10/12
    revDeltaMin:        1000
    revDeltaMax:        65534

                    :: generated by a vsSolutionBuildEvent v0.12.10.10901
```

P.S. So, I closed all Visual Studio instances. The way I reinstalled DllExport into the project is by manually removing stuff out from csproj, and then downloading a new `DllExport.bat` provided via release page under assets, so I replaced DllExport file and re-run config, and then installed it for the project using the prompt window.

**Comment by 3F** [comment]
@berbun Fixed build should point to e5554ca. But you still use f61ffe9 (public 1.6.3 release)

Please read the [documentation](https://github.com/3F/DllExport/wiki/DllExport-Manager): 

> the manager from any nightly builds will point to stable public package. Therefore, you need to select custom package via `-server` or `-pkg-link` to test specific build.

The most easy way to check it via GHR:

`DllExport -action Configure -force -pkg-link https://github.com/3F/DllExport/releases/download/CI-build-115/DllExport.1.6.3.nupkg`

**Comment by berbun** [comment]
Do you want me zip up the entire (fresh) solution, so you can take a look at the error yourself?

**Comment by berbun** [comment]
Yeah... Now I can notice it is on different revision:
```
    S_NUM:              1.6.3
    S_REV:              13999
    S_NUM_REV:          1.6.3.13999
    S_REL:
    bSha1:              e5554ca
    bName:              issue/106
    bRevc:              136
    Wizard .NET:        v4.0
    Configuration:      PublicRelease
    Platform:           AnyCPU
    cfgname:            Release
    revDeltaBase:       2016/10/12
    revDeltaMin:        1000
    revDeltaMax:        65534

                    :: generated by a vsSolutionBuildEvent v0.12.10.10901
```

And, yes, it has solved the issue.
/fixed

Thanks for the quick support! :)

**Comment by 3F** [comment]
Good! I've plan to release hotfixes ASAP, today or tomorrow. Follow the news.
