### ISSUE TITLE
Consider adding an "upgrade" functionality on the UI (config) prompt

### ISSUE THREAD

**Issue by berbun** [3F/DllExport#109]
An easier way to upgrade (and perhaps also downgrade) DllExport without using command line.

**Comment by 3F** [comment]
I'm not sure about demand for this feature in GUI option (I think you meant an Graphical part of UI).

Moreover, we're talking about today's separate Console-based manager and GUI Wizard(Configurator) part. I mean, then we need to combine this into something unified and so on.

hmm...

Well, why not to consider this issue later.

Thanks for suggestion.

**Comment by 3F** [comment]
Available since a998821. You can test it via related CI build. Planned for 1.7.
