### ISSUE TITLE
Add "Ordinal" property

### ISSUE THREAD

**Issue by OmegaExtern** [3F/DllExport#11]
So, it would allow to export methods at desired ordinal.

**Comment by 3F** [comment]
seems dup of #8

**Comment by OmegaExtern** [comment]
> seems dup of #8

Not duplicate.
#8 is to mimic ordinal counter to start from 1 instead of 0 (by default), and nothing more.
While this proposes to add a new property to `DllExportAttribute` class, which would allow to override the counter number.

**Comment by 3F** [comment]
initially it was a 'Ordinals should start from one (1), not zero (0)' with unclear description of what you trying to solve -_-

ok, suggestion to start from 1+ there, and to add as a common option here

**Comment by 3F** [comment]
![mod_ordinals](https://cloud.githubusercontent.com/assets/3246589/19013817/cc279702-87e4-11e6-930d-c3b13b014c3a.png)

you can check it with a2e9ba6
