### ISSUE TITLE
Fails when exist setup project

### ISSUE THREAD

**Issue by terranas** [3F/DllExport#114]
### Problem

I am using Visual Studio Professional 2019 on Windows 10. 
In case of exist MSI Setup Project (*.vdproj) in Solution, 
`DllExport.bat -action Configure` , or `DllExport.bat -action Restore` fails.

I got the message below:
```
[17:36:52.9237] [Fatal] ERROR-Wizard: The format `Debug` of configuration is not supported.
...
[17:36:52.9297] [Warn] MsgGuiLevel: '-1'
```

### How to reproduce

1. Add *.vdproj to Solution by "Microsoft Visual Studio Installer Projects" extension.
https://marketplace.visualstudio.com/items?itemName=visualstudioclient.MicrosoftVisualStudio2017InstallerProjects

2. run `DllExport.bat -action Configure`

**Comment by 3F** [comment]
@terranas, Thanks for the report. The problem was found in MvsSln:

You can patch **temporarily** your sln file before our fixes. Find this:

```sln
{GUID of your .vdproj}.Debug|solution_platform.ActiveCfg = Debug
```

Then just add something to the end, for example "|Any CPU":

```sln
{C44BFE7A-DBED-411A-8073-C88663B18ADC}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
......................................................................^^^^^^^^^ just add this
```

**Comment by 3F** [comment]
An old unclear issue #91 looks like contains the same problem. But the author did not provide any information for that.

I remind everyone that simple steps to reproduce the problem are very important to solve this ASAP!

**Comment by terranas** [comment]
@3F Thank you!
It worked well by your temporarily solution with v1.6.4.15293.

**Comment by 3F** [comment]
@terranas, Please keep open this issue until it's resolved. Fixes depends on MvsSln. Follow the news.

**Comment by 3F** [comment]
@terranas, Please check fixes before public release:

`DllExport -force -pkg-link https://github.com/3F/DllExport/releases/download/CI-build-121/DllExport.1.6.4.nupkg`

or manually: https://github.com/3F/DllExport/releases/tag/CI-build-121

**Comment by terranas** [comment]
@3F I tried CI-build-121,
but both `DllExport.bat -action Configure` and `DllExport.bat -action Restore` fails yet.

**Comment by 3F** [comment]
Please use `-force` and `-pkg-link` keys like I mentioned above. Or manually replace binaries from CI-build-121

Because:

> manager from any nightly builds will point to stable public package
[[?](https://github.com/3F/DllExport/wiki/DllExport-Manager#nightly-builds)]

**Comment by 3F** [comment]
MvsSln 2.4 is just released. [changelog:](https://github.com/3F/MvsSln/blob/master/changelog.txt)
```
* FIXED: "The format ... of configuration is not supported". Issue #19.
...
```

@terranas 

I don't see any confirmation from you but this was reproducible also for me. Thus, you have a few hours (or less) before today's release (means if you still have something). Thanks.
