### ISSUE TITLE
I think i have same issue with 4.7 target framework:

### ISSUE THREAD

**Issue by adymilk** [3F/DllExport#115]
I think i have same issue with 4.7 target framework:

---Update 
after installed build tool 2015 it worked
----

Error The "DllExportAppDomainIsolatedTask" task failed unexpectedly.
System.ArgumentException: Requested value 'Version47' was not found.

Server stack trace: 
   in System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   in System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   in System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   in RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.<>c__DisplayClass8.<GetGetToolPathInternal>b__7(Version version, String toolName) in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:riga 568
   in RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.TryToGetToolDirForFxVersion(String toolFileName, Func`3 getToolPath, String& toolDirectory) in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:riga 725
   in RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateToolPath(String toolFileName, String currentValue, Func`3 getToolPath, String& foundPath) in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:riga 698
   in RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateFrameworkPath() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:riga 680
   in RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateInputValues() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:riga 396
   in RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.Execute() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:riga 264
   in RGiesecke.DllExport.MSBuild.DllExportAppDomainIsolatedTask.Execute() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\DllExportAppDomainIsolatedTask.cs:riga 241
   in System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   in System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   in System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   in System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   in Microsoft.Build.Framework.ITask.Execute()
   in Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   in Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	EasyLoad

_Originally posted by @bbday in https://github.com/3F/DllExport/issues/29#issuecomment-349252880_

**Comment by adymilk** [comment]
Thanks for share. It is helpfull

**Comment by 3F** [comment]
I remind everyone,

Our DllExport have no this problem even without my temp solution from #29 
* https://github.com/3F/DllExport/issues/95#issuecomment-475863295

**Comment by 3F** [comment]
Yep, just found it again, after #191

> Originally posted by @**bbday** in #29 (comment)
> ...
> Thanks for share. It is helpfull

Absolutely no respect to my work <_< Thanks to **me**,

> try to install msbuild tools (~20 MB):
https://github.com/3F/DllExport/issues/29#issuecomment-284259126

Points exactly to *"Microsoft Build Tools 2015"* which solves the problem mentioned by @**bbday** later.

Anyway, again, regarding to #191

2021, I remind everyone, that was a **temp solution**. Modern 1.7.4 must work fine without everything that I suggested from original issue. For other case, please open a new one.
