### ISSUE TITLE
Updates on supporting .NET Core

### ISSUE THREAD

**Issue by PatVax** [3F/DllExport#119]
I read in some of comments on this repo that .NET Core support is planned sometime Autumn 2019. I am going to work on a project when the DllExport functionality would be needed on .NET Core Environment. So I wanted to ask for an update if there was any progress in this. Is this legitimate to assume that .NET Core support will be added during next month or month and a half? I even tried looking into the code myself but I didn't knew where should I begin to possibly port the project to .NET Core.

**Comment by 3F** [comment]
Please use #90 for any updates.
