### ISSUE TITLE
DllExport & UnmanagedExports 

### ISSUE THREAD

**Issue by HeroinGyrl** [3F/DllExport#122]
Hello.

I m using the UnmanagedExports Nuget package and it works for me in framework 4.7 but if I upgrade my framework version to 4.8 I m getting a error with version48 in the UnmanagedExports. 

now I tryed to configure DllExport It builds without any error but the DLLExport not works. my .dll library is not exporting the functions with [DllExport] 

this is not a issue with my code because with UnmanagedExports it works.

regards.

**Comment by 3F** [comment]
**Very** informative issue. Did you try to read [something](https://github.com/3F/DllExport/blob/4db7142930fed74e3cb2a168b97350325a219257/.github/issue_template.md#how-to-reproduce) before reporting?

I personally don't see problems for 4.8

**Comment by HeroinGyrl** [comment]
I do not know what I do wrong. but [DllExport] seems to do nothing for me with the DllExport package.
But for the UnmanagedExports [DllExport] works for me.
With not works means that there is no build error it just wont export functions.

So If I use the UnmanagedExports package and upgrade my framework from 4.7 to 4.8 I m getting a compiler error:

> Severity Code Description Project file line suppression state
Error Unexpected error with the DllExportAppDomainIsolatedTask task.
System.ArgumentException: The requested value "Version48" could not be found.

If there is a fix for this issue I can just use the UnmanagedExports package.

**Comment by HeroinGyrl** [comment]
okay.. I found the issue It creates 2 different files..
not working file:  `x64\Debug\`
working file: `x64\Debug\x64\`

why not just insert that directly in `x64\Debug\` and what does the folder After and Before means?

**Comment by 3F** [comment]
@HeroinGyrl 

> I do not know what I do wrong.

This is what I'm talking about. Please provide at least something. **I don't even know what version** and what are you doing at all. Did you understand me?

Please follow [this minimal info](https://github.com/3F/DllExport/blob/4db7142930fed74e3cb2a168b97350325a219257/.github/issue_template.md#how-to-reproduce).

Therefore, Can you send here such as **diag log** ? **.csproj** ? or more about your environment? again, just please something. 

Moreover, `"VersionXX" could not be found` usually points to this: #29 ( -> https://github.com/3F/DllExport/issues/95#issuecomment-475863295)

Thanks!

**Comment by HeroinGyrl** [comment]
Issue found [here](https://github.com/3F/DllExport/issues/122#issuecomment-546705657)
It builds 2 different files.

**Comment by 3F** [comment]
@HeroinGyrl 

I'm not sure what are you trying. But x64/x86 folders will be used when configuring **both** archs. Just select what you need if you only need x64

> what does the folder After and Before means?

Just disable option `Keep intermediate Files (IL Code, Resources, ...)` because this is not what are you looking for (brackets)

Also, I don't understand how does it related to `"VersionXX" could not be found` problem.

Thus, if you still have this, please reopen this issue for details as I said above. Thanks!

**Comment by HeroinGyrl** [comment]
The build error with `VersionXX could not be found` is in the [UnmanagedExports](https://www.nuget.org/packages/UnmanagedExports) package. by upgrading from 4.7 to 4.8 Framework.

the issue that [DllExport] not worked was that the file was in another folder.
It was a problem with my configuration I made there something wrong. 
but now everything works. 

regarding.

**Comment by 3F** [comment]
I see. Thanks for the reply!

**Comment by Pratikkulkarni-93** [comment]
HI @HeroinGyrl 

Am getting the same issue, could you guide me how to resolve this.

thanks

**Comment by HeroinGyrl** [comment]
hey @Pratikkulkarni-93 it's a long time since I opened that issue.
can you provide screenshot of your configurations.

**Comment by Pratikkulkarni-93** [comment]
Hi HeroinGyrl ,

thanks for your rply

with Dllexport i could create the dll but its not working

could you tell me which configuration needs to set

Thanks and Regards
Pratik P. Kulkarni
