### ISSUE TITLE
Failed to resolve assembly...

### ISSUE THREAD

**Issue by esso23** [3F/DllExport#127]
Hi,

I have a problem when using latest version with .NET Standard 2.1 (same problem occurs when I use .NET Core 3.1).
The error happens when building:

> 'Failed to resolve assembly: 'dllexport_issue.dep, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'	dllexport_issue	D:\Sync\Projects\dllexport_issue\packages\DllExport.1.7.0-beta\tools\net.r_eg.DllExport.targets	74'

Basically I have ClassLibrary1 referencing ClassLibrary2 and in some cases DllExport cannot resolve ClassLibrary2 assembly when creating exports for ClassLibrary1.
I tried to isolate the problem and the build task fails when there is an Attribute that has an Enum property which is initialized in Attribute constructor (not sure that's the ACTUAL problem, but when I was adding things one by one, that's where it broke). See attached repro.

* `-version`: v1.7-beta
* Project type: 64-bit netstandard 2.1
* Environment ( VS, MSBuild, ...): Visual Studio 16.4, MSBuild, Windows 10 Pro, .NET Core 3.1 SDK

Here is complete solution with minimum repro. Just compile 'dllexport_issue' project and error occurs:
'Failed to resolve assembly: 'dllexport_issue.dep, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'	dllexport_issue	D:\Sync\Projects\dllexport_issue\packages\DllExport.1.7.0-beta\tools\net.r_eg.DllExport.targets	74	'
[dllexport_issue.zip](https://github.com/3F/DllExport/files/3940009/dllexport_issue.zip)

Edit: Maybe it's worth to note I am porting code to .NET Standard 2.1 from .NET Framework 4.7.2 where I was also using DllExport (1.6.5) and everything worked fine.

**Comment by 3F** [comment]
Confirm. Thanks for the report and attached sample!

> .NET Framework 4.7.2 where I was also using DllExport (1.6.5) and everything worked fine.

Yes, please use this before fixing problem. I'll try to review issue for 1.7 beta2.

**Comment by 3F** [comment]
Please test applied solution through latest beta releases.
