### ISSUE TITLE
Exported name mismatched

### ISSUE THREAD

**Issue by Executor-Cheng** [3F/DllExport#129]
Using v1.7-beta2, checked `Use our IL Assembler`, TargetFramework=netcoreapp3.1, the following method will be exported as "Test", not "test123".
```CSharp
[DllExport("test123", CallingConvention.StdCall)]
public static int Test()
    => 0;
```
But if I use `CallingConvention.Cdecl`, the exported name will be "test123".

**Comment by 3F** [comment]
nice catch for 1h ago released version :) I can't even imagine where this broken part if cdecl ok. Is this reproducible for prev beta?
I'll look into later, just 3 AM on my watch. Thanks for the report!


On 14.12.2019 2:59, Executor wrote:

Using v1.7-beta2, checked Use our IL Assembler, TargetFramework=netcoreapp3.1, the following method will be exported as "Test", not "test123".

[DllExport("test123", CallingConvention.StdCall)]
public static int Test()
    => 0;

But if I use CallingConvention.Cdecl, the exported name will be "test123".

**Comment by Executor-Cheng** [comment]
Sorry, I made a mistake. It seems that the bug is related to `DllExportAttribute.CallingConvention` property.
Modify this property will cause the bug.
```CSharp
[DllExport("test123")] // Correct
[DllExport("test123", CallingConvention.Cdecl)] // Incorrect
[DllExport("test123", CallingConvention = CallingConvention.Cdecl)] // Incorrect
```
Previous version is ok.

**Comment by 3F** [comment]
@Executor-Cheng, Please check fixes using the following CI build: https://ci.appveyor.com/project/3Fs/dllexport-ix27o/builds/29539703/artifacts

I'll try to prepare new release ASAP.

**Comment by Executor-Cheng** [comment]
Great! The problem has been solved! Thank you for your quick fix :)

**Comment by 3F** [comment]
Done. Please use **Beta3** release.
