### ISSUE TITLE
DllExport crashing with proxy authentication error

### ISSUE THREAD

**Issue by kcl93** [3F/DllExport#133]
How to reproduce:

Hello,
I get an error message "The remote server returned an error: (407) Proxy Authentication Required." when trying to execute DllExport on some selected computers at work. It happens Always when trying to Access the DllExport.bat both during Building in VS 2017 or while simply starting it in the Explorer.
The source of issue itself sounds very much like this here (I can't track it down myself): https://stackoverflow.com/questions/2581609/the-remote-server-returned-an-error-407-proxy-authentication-required

* `-version`: v1.6.5.4044
* `-build-info`: ?
* Full command to Manager: does not matter
* Project type: Class library
* Environment ( VS, MSBuild, ...): VS2017

Used configuration:

Standard

Optional Project files / Samples:

Nothing

log (after removing '@echo off' from the Batch file):

[Output.txt](https://github.com/3F/DllExport/files/3978837/Output.txt)

**Comment by 3F** [comment]
Thanks for the report!

> log (after removing '@echo off' from the Batch file):

:) Please use `-debug` key, eg.: `DllExport -debug ...`

> "The remote server returned an error: (407) Proxy Authentication Required."

Can you try to pass manually your credential before I start inspecting issue. I mean, does this work for you: `-proxy [usr[:pwd]@]host[:port]` [[?]](https://github.com/3F/DllExport/wiki/DllExport-Manager#proxy)

**Comment by kcl93** [comment]
Hello :)

Thanks for the quick reply! This is the output when using the -debug option:

> C:\Users\SomeUser>C:\SomeProject\src\DllExport.bat -debug
> [ 8:31:12,62 ] dxpName =  DllExport
> [ 8:31:12,63 ] dxpVersion =  1.6.5
> [ 8:31:12,64 ] -sln-dir =
> [ 8:31:12,64 ] -sln-file =
> [ 8:31:12,65 ] -metalib =
> [ 8:31:12,66 ] -dxp-target =
> [ 8:31:12,66 ] -wz-target =  tools/net.r_eg.DllExport.Wizard.targets
> [ 8:31:12,70 ] wPkgPath =  packages\\DllExport.1.6.5
> [ 8:31:12,71 ] -pkg-link =
> [ 8:31:12,71 ] -server =  https://www.nuget.org/api/v2/package/
> [ 8:31:12,72 ] GetNuTool call:   /p:ngserver="https://www.nuget.org/api/v2/package/" /p:ngpackages="DllExport/1.6.5" /p:ngpath="packages\\" /p:proxycfg=""
> 
>   GetNuTool 1.7.0.18022_4bc1dfb - github.com/3F
>   =========
> 
> Getting `DllExport/1.6.5` ... The remote server returned an error: (407) Proxy Authentication Required.
> Something went wrong. Try to use another keys.

There indeed seem to be some proxy configuration missing. I tried passing it with -proxy but I could not get it to work (likely due to myself using the wrong proxy settings as I am not exactly sure what the right ones are for our office).
It would be great if DllExport could just use the standard proxy settings as all other programs on the related computers work without problems.

I just realized, that you also provide an offline version of DllExport. This one works fine for me with the only small issue that I also have to copy all other NuGet packages to "packages.offline" as Visual Studio does not seem to look at "packages" when a "packages.offline" folder is present.

**Comment by 3F** [comment]
@kcl93 

GetNuTool now contains related fixes. Please test CI build: https://ci.appveyor.com/project/3Fs/dllexport/builds/30047860/artifacts
* https://ci.appveyor.com/api/buildjobs/51qptg0s80khgk57/artifacts/bin%2FRelease%2FDllExport.bat

More probably I will also prepare 1.6.6 release before 1.7. Please report me about problems if still.

**Comment by kcl93** [comment]
I have tested your updated batch file and it now works perfectly for me on all machines. Thanks! :)

**Comment by 3F** [comment]
Good! Thanks for the feedback.


On 13.01.2020 12:18, kcl93 wrote:

I have tested your updated batch file and it now works perfectly for me on all machines. Thanks! :)
