### ISSUE TITLE
SEHException on .NET Core 3.1

### ISSUE THREAD

**Issue by esso23** [3F/DllExport#134]
Hello again,
I have another problem, this one seems to be pretty serious (unless I'm doing something wrong). Basically I'm unable to do anything with DllExport in .NET Core 3.1/.NET Standard 2.1 environmnent due to SEHException which appears everytime I call exported method (when called from native code it also crashes without any information about the crash).

**How to reproduce:** Create .NET Core 3.1 DLL and export one void parameterless method. Import it in .NET Core 3.1 console app and call it.
Application will throw an exception:

> System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'

**VS Solution:** 
[DllExport_SEH.zip](https://github.com/3F/DllExport/files/4059077/DllExport_SEH.zip)
Just run ImportApp to reproduce.

* `-version`: DllExport v1.7-beta3
* Environment ( VS, MSBuild, ...): Visual Studio 16.4.0 on Windows 10 Pro

**Used configuration:**
Library: .NET Core 3.1.100 x64
Console App: .NET Core 3.1.100 x64

**Comment by 3F** [comment]
dup #132 
Please follow my instructions there.
