### ISSUE TITLE
Build fails if declare a Interface with default method

### ISSUE THREAD

**Issue by marcussacana** [3F/DllExport#138]
How to reproduce:
- Declare a interface with the new C# 8.0 "default method" feature
- Declare any dll export

... 

* Version: 1.7.0
* Project type: .net Core Library
* Environment ( VS, MSBuild, ...):  VS19 Preview

...

Samples:
```csharp
using System.Runtime.InteropServices;

namespace TEST
{
    public static class Main
    {
        [DllExport(CallingConvention.StdCall)]
        public static int Test(int Dbg) => Dbg;

        static dbg test = new dbg();
    }

    public class dbg : Dbg
    {
        public void Test() { }
    }

    public interface Dbg {
        public virtual void Test() { }
    }
}
```
...

log:
[build.log](https://github.com/3F/DllExport/files/4208660/build.log)

Screenshot:
![image](https://user-images.githubusercontent.com/10576957/74590800-9348f980-4ff0-11ea-882e-b033e2f2b717.png)

**Comment by marcussacana** [comment]
Since is more like a 'unsupported feature' of a bug, maybe it would be better to create a new feature issue instead of a bug?

**Comment by 3F** [comment]
I am watching `DllExportOurILAsm = false` and empty 
`DllExportILAsmCustomPath` in your log;
Try again with modern assembler which should provide features related to 
.NET Core 3 (C# 8.0 specified for 3.x as I know).

**Comment by marcussacana** [comment]
`DllExportOurILAsm = true` solved, thank you.
