### ISSUE TITLE
Re# doesn't play nicely with dynamic definition of namespace

### ISSUE THREAD

**Issue by OmegaExtern** [3F/DllExport#14]
The following keep poping up across screen (also notice "Cannot resolve symbol"):
![image](https://cloud.githubusercontent.com/assets/6441892/18794854/e5c7ae0a-81c1-11e6-98b9-f4c69ac45625.png)

Though I do like idea of "dynamic definition of namespace", it is very annoying and clearly was not made to support Re#, apparently it was introduced in #2. Which is not the case with (original) [UnmanagedExports](https://www.nuget.org/packages/UnmanagedExports) NuGet package (where namespace is static).

**Comment by 3F** [comment]
hmm, object model should be fully updated automatically... need to think

this only with Re# ?

**Comment by jonsq** [comment]
I'm brand new to this repo, but it looks like vb.net is having the same trouble?  Using Visual Studio 2010 + .Net 4.0 + Nuget package version 1.3.0.

![image](https://cloud.githubusercontent.com/assets/962123/18796384/04018696-8197-11e6-93f7-2f6aeb881a08.png)

**Comment by 3F** [comment]
:) strange, it's not reproduced for me at all.

Did I understand correctly that problem **only** with tips from IDE above and export works well ?

What after restarting IDE ? or reloading of projects/solution when it installed ?

**Comment by jonsq** [comment]
As far as I can tell, it's not causing any problems.  Just instead of using the custom namespace, it's using that really long string.

![image](https://cloud.githubusercontent.com/assets/962123/18797391/bf5390c0-819b-11e6-8bca-42b75e7a0a9c.png)

**Comment by 3F** [comment]
+jonsq

I see, thanks !

However it not reproduced for me :( need to think

my gif illustration here: https://github.com/3F/DllExport/issues/6#issuecomment-243003856

All details about this here: [Dynamic definitions of namespaces](https://github.com/3F/DllExport/issues/2)

**What after restarting IDE ?**

**Comment by OmegaExtern** [comment]
> What after restarting IDE ? or reloading of projects/solution when it installed ?

Already tried. Nothing have changed.
A program compiles fine though.

One more thing, once that namespace (with DllExportAttribute class) is imported, it magically makes a program uncompilable:

> CS0246: The type or namespace name 'D3F00FF1770DED978EC774BA389F2DC901F4' could not be found (are you missing a using directive or an assembly reference?)

**Comment by OmegaExtern** [comment]
Installation log (I have used `ExportedLibrary` for dynamic namespace):
```
Attempting to gather dependency information for package 'DllExport.1.3.0' with respect to project 'ExportedLibrary', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'DllExport.1.3.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'DllExport.1.3.0'
Resolved actions to install package 'DllExport.1.3.0'
Adding package 'DllExport.1.3.0' to folder '...\packages'
Added package 'DllExport.1.3.0' to folder '...\packages'
Added package 'DllExport.1.3.0' to 'packages.config'
Executing script file '...\packages\DllExport.1.3.0\tools\install.ps1'...


Name                  : DllExportNamespace
UnevaluatedValue      : ExportedLibrary
IsEnvironmentProperty : False
IsGlobalProperty      : False
IsReservedProperty    : False
Xml                   : Microsoft.Build.Construction.ProjectPropertyElement
Predecessor           : 
IsImported            : False
EvaluatedValue        : ExportedLibrary
Project               : Microsoft.Build.Evaluation.Project

Name                  : DllExportNamespace
UnevaluatedValue      : ExportedLibrary
IsEnvironmentProperty : False
IsGlobalProperty      : False
IsReservedProperty    : False
Xml                   : Microsoft.Build.Construction.ProjectPropertyElement
Predecessor           : 
IsImported            : False
EvaluatedValue        : ExportedLibrary
Project               : Microsoft.Build.Evaluation.Project

defNS: (...\packages\DllExport.1.3.0\lib\net20\DllExport.dll); (ExportedLibrary)
1489
4
1457
The DllExport Library has been modified !
namespace: ExportedLibrary
Details here: https://github.com/3F/DllExport/issues/2


Successfully installed 'DllExport 1.3.0' to ExportedLibrary
========== Finished ==========
```

I have found a way-around this, that is, create own `DllExportAttribute` class and use it (seems like #2 has failed a lot)..

**Comment by 3F** [comment]
> seems like #2 has failed a lot

I see only report from #6 and also not for all. But, I already pushed changes for this - https://ci.appveyor.com/project/3Fs/dllexport/history, so **probably it already fixed** (I don't see any replies from this guys) - 

*when I will get a time for this project, I will start new release with this changes (+some changes from current issues)*

For this issue:

**! btw, please check this problem with latest changes** from master - bcfa5ccb

need to details, I will look it later because it also should be ok. `The DllExport Library has been modified !`  Therefore, the `'D3F00FF1770DED978EC774BA389F2DC901F4` cannot be at all ([see 3 item](https://github.com/3F/DllExport/issues/2#issuecomment-231593744))

 The main problem how to reproduce it for me :(

**Comment by OmegaExtern** [comment]
> btw, please check this problem with latest changes from master

Ok. I have just tested this with nightly build NuGet package ([link](https://ci.appveyor.com/api/buildjobs/9fj1e1otwts3bu9w/artifacts/bin%2FRelease%2FDllExport.1.3.0.nupkg)). Restarted VS2015, and created an empty console application, and then added a reference to local NuGet package. Still, nothing have changed.
Here is installation log of this time (now I have used "System.Runtime.InteropServices" as dynamic namespace):
```
Attempting to gather dependency information for package 'DllExport.1.3.0' with respect to project 'ExportedLibrary', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'DllExport.1.3.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'DllExport.1.3.0'
Resolved actions to install package 'DllExport.1.3.0'
Adding package 'DllExport.1.3.0' to folder '...\packages'
Added package 'DllExport.1.3.0' to folder '...\packages'
Added package 'DllExport.1.3.0' to 'packages.config'
Executing script file '...\packages\DllExport.1.3.0\tools\install.ps1'...


Name                  : DllExportNamespace
UnevaluatedValue      : System.Runtime.InteropServices
IsEnvironmentProperty : False
IsGlobalProperty      : False
IsReservedProperty    : False
Xml                   : Microsoft.Build.Construction.ProjectPropertyElement
Predecessor           : 
IsImported            : False
EvaluatedValue        : System.Runtime.InteropServices
Project               : Microsoft.Build.Evaluation.Project

Name                  : DllExportNamespace
UnevaluatedValue      : System.Runtime.InteropServices
IsEnvironmentProperty : False
IsGlobalProperty      : False
IsReservedProperty    : False
Xml                   : Microsoft.Build.Construction.ProjectPropertyElement
Predecessor           : 
IsImported            : False
EvaluatedValue        : System.Runtime.InteropServices
Project               : Microsoft.Build.Evaluation.Project

set new namespace: (System.Runtime.InteropServices) - (...\packages\DllExport.1.3.0\lib\net20\DllE
xport.dll)
The DllExport Library has been modified !
namespace: System.Runtime.InteropServices
Details here: https://github.com/3F/DllExport/issues/2


Successfully installed 'DllExport 1.3.0' to ExportedLibrary
========== Finished ==========
```

**Comment by 3F** [comment]
@OmegaExtern

just noticed your new edit 2 :)

> just move DllExportAttribute class in the same namespace where DllImport

it already was in v1.1 ! but after short discussion with Robert I decided to provide more compatible solution.

He said simply: 

> What you should never, ever do is putting stuff in a general namespace like System.Runtime.InteropServices.

I wrote:

> I do not think so :) ...

**...** and main part of my thoughts [here](https://github.com/3F/DllExport/issues/2#issue-164662993) as an my short explanation to Robert that DllExport it's special case.

with important note about problems that can be - `DllExport & InteropServices it more likely a theoretical-potential problems, but yes, conflicts are possible.` That I said before.

My final decision you already know, and mainly I like it more, because I want to use `System.Runtime.InteropServices` in my X projects, but not everyone likes it and wants to something other (that soundly)

bugs ?

bugs everywhere

![_bugs everywhere](https://cloud.githubusercontent.com/assets/3246589/18993200/be1ae2d2-872a-11e6-81cf-4733cfab4fb1.png)

just to fix it :)

-----

I'm still not see any errors :( I also tried in VM with different locale etc. but no result. All works fine, damn :)

@OmegaExtern @jonsq 

ok ! I already started new GUI configurator, that also affects on this feature. So, please test it from develop branch

**Comment by 3F** [comment]
I'm still not see any errors :( I also tried in VM with different locale etc. but no result. All works fine, damn :)

@OmegaExtern @jonsq 

ok ! I already started new GUI configurator, that also affects on this feature. 

![gui_conf](https://cloud.githubusercontent.com/assets/3246589/18993848/df5aab46-872d-11e6-8a81-9f32f9aa2502.png)

So, please test it from develop branch - ba0da455

**Comment by 3F** [comment]
please report about result (latest changes: 00bede75eab see binaries from CI)

**Comment by 3F** [comment]
v1.4:

```
    * NEW: GUI Configurator with updated ddNS features.
    * OTHER: other possible changes and fixes.
```

reopen if needed

**Comment by OmegaExtern** [comment]
I'm back.
So, I installed fresh v1.4 package. Screenshot of settings:
![image](https://cloud.githubusercontent.com/assets/6441892/19368339/dbc1950e-919f-11e6-983b-37e58497af05.png)

And apparently this issue is still a thing. Reopen it.

**Comment by 3F** [comment]
:) holy hedgehogs 

please attach all files from your `...\packages\DllExport.1.4.0\lib\net20\`

**Comment by 3F** [comment]
:) holy hedgehogs 

please attach all files from your `...\packages\DllExport.1.4.0\lib\net20\`

**Comment by OmegaExtern** [comment]
Compressed in Zip file: [net20.zip](https://github.com/3F/DllExport/files/528330/net20.zip)

**Comment by OmegaExtern** [comment]
> in your project file (.csproj etc)

Okay, maybe this would help:
In project file, "DllExportNamespace" seems to be invalid child element, however Re# doesn't say the same for "DllExportOrdinalsBase" (the latter seems to be valid).

See source for project file, [here](https://gist.github.com/OmegaExtern/24d09c903e7d25e0018541ec7bb1700d).

**Comment by 3F** [comment]
still all works fine (14.0.25421.03 Update 3)

but I found possible problem in **0x007A7-0x007A8** however strange that VS works correctly for me -_- 

I changed 2 bytes manually for your library, can you check:

* Close VS IDE
* replace DllExport.dll from me - [mod_DllExport.zip](https://github.com/3F/DllExport/files/528375/mod_DllExport.zip)
* Open this project again

---

why you think that's invalid ?

```xml
...
<DllExportNamespace>ExportedLibrary</DllExportNamespace>
...
```

**Comment by 3F** [comment]
by the way, again, you should not see sequence D3F00FF1770DED978E... at all, it's marker only, that can be updated for zero-based sequence that will be considered as a null-terminated string.

Therefore GAC ? I remembered this https://github.com/JamesNK/Newtonsoft.Json/issues/647 or some other cache. 
Can you check this or something else ?

**Comment by OmegaExtern** [comment]
> 14.0.2542**1.03** Update 3

Mine is 14.0.2542**5.01** Update 3. Your VS is older.
Re# is 2016.2.2  Build 106.0.20160913.91321.
For those who don't know, there is an option to disable the popup though, in options search for `Show the Import namespace action using popup`:
![Show the Import namespace action using popup](https://cloud.githubusercontent.com/assets/6441892/19404385/de7b9e06-926d-11e6-9ff0-aa9b9a62617a.png)

> I changed 2 bytes manually

Ok, `0x30 0x30` to `0x00 0x00` at location `0x7A7`.

> can you check

Ok. Finally:
![image](https://cloud.githubusercontent.com/assets/6441892/19404564/36bbe7d2-926f-11e6-86ed-4bfd087abf98.png)

-------------------

So... Why the two bytes must be manually changed?

**Comment by OmegaExtern** [comment]
> why you think that's invalid ?

It is not me, it is Re# that reported it, see (even after above manual DllExport patch):
![image](https://cloud.githubusercontent.com/assets/6441892/19404686/7c32edf0-9270-11e6-91c6-a4d30bb3617a.png)

But, this doesn't really matter, right?

**Comment by 3F** [comment]
> Mine is 14.0.25425.01 Update 3. Your VS is older.

how about very older VS2010 from +jonsq ?

> Ok. Finally:

o_O I didn't understand - this works or not ?

> Why the two bytes must be manually changed?

`0x30 0x30` is not correct for `for zero-based sequence that will be considered as a null-terminated string.` see above

**just a typo**, later I will fix it ! yesterday I changed it manually because it faster to check on your prepared project.

> It is not me, it is Re# that reported it

it's warning of schema only - see xmlns

> But, this doesn't really matter, right?

yes, for this issue it should not be related at all. And mainly this as part of full identifier to work with data via Cecil

**Comment by OmegaExtern** [comment]
> I didn't understand - this works or not ?

Yes, your manual patch worked (see screenshots?).

**Comment by 3F** [comment]
> Yes, your manual patch worked

Good !

How about [Object Browser](https://github.com/3F/DllExport/issues/14#issuecomment-249270981) ?


*and note for `0x30 0x30 is not correct for for zero-based ...` I mean like for our case, well I think you understood me :)*

**Comment by OmegaExtern** [comment]
> How about Object Browser ?

I have checked it already, and I could not find "ExportedLibrary" project nor anything about "DllExport". I have selected to search all components and still nothing... Possible VS bug?

**Comment by 3F** [comment]
@OmegaExtern 

* ca2d68b solves problem with `0x30 0x30`, as I said just a typo:  `sizeof(UInt16)` -> `sizeof(UInt16) * 2`
* 38c5388 I also added Cecil variant for ddNS features. Now you can try both variant with GUI Configurator. Or set msbuild property `DllExportDDNSCecil` as true

*And I tested both variant for VS2010 v10.0.30319.1 (without SP1) in VM*

**Comment by 3F** [comment]
Please test latest changes, for example d17e335
I've plan new release on this week or earlier

**Comment by OmegaExtern** [comment]
I am waiting for nightly build, or [is this the build d17e335](https://ci.appveyor.com/api/buildjobs/b6wolranp0c7fbb6/artifacts/bin%2FRelease%2FDllExport.1.4.0.nupkg)?
If that's build d17e335, then you didn't solve it:
![image](https://cloud.githubusercontent.com/assets/6441892/19672084/0235311e-9a74-11e6-99fc-9acb40b264fd.png)

If it is not build d17e335, please upload it; I can't be bothered to compile this from source code..

**Comment by 3F** [comment]
amazing o_o
yes, I was waiting for the results of latest changes i.e. the d17e335 should include all fixes for this.

Did you check both type of changes - **Cecil** and **Direct-Mod** ? this is for both options ?

**Comment by OmegaExtern** [comment]
Ok, this is weird, but there's some sense. It happens with both, Cecil and Direct-Mod.
So, I have reloaded a project and it fixed itself. Well, well, well, unload project (**before** NuGet package is installed, or **before** a project file is modified), then load project (**after** NuGet package is installed, or **after** a project file is modified).
I sure that will fix it, like **100% sure**.

**Comment by 3F** [comment]
@OmegaExtern 

just for checking: the any install/remove operation for this package will load our assemblies into main domain of VS !

I used this before to avoid problem with loading of .net assemblies:

```powershell
powershell -Command "Import-Module (Join-Path $ToolsPath Configurator.dll); Set-Configuration -Dll $asmpath"
```

it was simply, but now I need to provide via `-Command` a complex objects (EnvDTE.Project & Microsoft.Build.Evaluation.ProjectCollection), and seems it's not possible (I'm not sure, I do not use powershell so often) like `-ProjectDTE $project -ProjectsMBE $gpc` etc.

of course I can prepare all this inside like [in my other plugin](https://github.com/3F/vsSolutionBuildEvent) (that contains complex support of EnvDTE & MS Build.Evaluation) , but I don't want hard impl. for DllExport

Therefore, the other easy way to use through temp assemblies:

```powershell
$dllConf = Get-TempPathToConfiguratorIfNotLoaded 'net.r_eg.DllExport.Configurator.dll' "$toolsPath"
if($dllConf) {
    Import-Module $dllConf; 
}

Set-Configuration -MetaLib "$metaLib" -InstallPath "$installPath" -ToolsPath "$toolsPath" -ProjectDTE $project -ProjectsMBE $gpc;
```

*ah yes, I also thought about [this](https://github.com/3F/Conari/issues/5) but for common solution I have no time yet. later*


**So !** if you already have installed package, to full upgrade on new version, please restart IDE **if [remove] button is clicked before**.
