### ISSUE TITLE
After installing ur "package" had some issue in namespase

### ISSUE THREAD

**Issue by RiseeeAgainst** [3F/DllExport#142]
. . .

I've done all actions like in the video tutorial (wirking wit netstandard project) and all works, but for using DllExport attributes I need to include namespace, that after installing looks like 

-----------

*(Remove this section after reading. Click `Preview` tab for convenience)*

## ! Important

1. **Please** use our [wiki](https://github.com/3F/DllExport/wiki) first. +Available [**Q&A** list](https://github.com/3F/DllExport/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion).

2. Please try to use MSDN, stackoverflow, and other relevant places for understanding common practice with P/Invoke, scalar & unmanaged native types, marshaling, .net-domains, multithreading, ... ~something other. Because this is not directly related to our project to teach you programming. We can try to help you anyway, but please have a *conscience.*

### If you're ready to ask something

1. **Try to use** only [GitHub for your attachments and screenshots](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) instead of other places. It's free, it's enough.
2. **Do not** put inside message any very long text data ( ~ 10 Kb+ time for attachments ). Means only as file (text-based, or zip, etc). Because we're receiving this notification through email, so it's really ... [100K+](https://github.com/3F/DllExport/issues/71)
3. Please try to use [**basic formatting**](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to avoid code dancing 🕺 across the page.

**Comment by RiseeeAgainst** [comment]
D3F00FF1770DED978EC774BA389F2DC901F4.B00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.C00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.D00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.E00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.F00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;

**Comment by 3F** [comment]
@RiseeeAgainst For errors you need use [`Bug Report` template](https://github.com/3F/DllExport/issues/new?labels=bug&template=bug_report.md)!

Just look at this: We don't even know what version, or what environment, or something at all.

Please **reopen this issue** after update using a [correct issue template](https://github.com/3F/DllExport/issues/new?labels=bug&template=bug_report.md). And ... >>> *(Remove this section after reading ...*
