### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by NickAcPT** [3F/DllExport#143]
Steps to reproduce:
I created a .Net Core 3.1 class library project. 

* `DllExport -version`: .NET DllExport 1.7.0.60761+0a002a7
* Used Visual Studio / MSBuild : Version 16.6.0 Preview 1.0

Information from *`Data`* tab or log data: 
```
SignAssembly: 
Identifier: 4ABE2AFA-5379-4FD4-855F-EE48A89B797C
Instance: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\amd64\MSBuild.exe
Project path: 
Action: Configure
PlatformTarget: 
TargetFramework: 
TargetFrameworks: 
TargetFrameworkVersion: 
RootNamespace: 
AssemblyName: 
MgrArgs: 
MetaLib: tools\raw\lib\net20\DllExport.dll
MetaCor: tools\raw\lib\netstd\DllExport.dll
Proxy: 
StoragePath: .net.dllexport.targets
ddNS: 
ddNS max buffer: 500
UseCecil: True
intermediateFiles: False
timeout: 30000
RootPath: C:\Users\NickAc\Source\Repos\WinTabby\
PkgPath: C:\Users\NickAc\Source\Repos\WinTabby\packages\\DllExport.1.7.0\
SlnFile: 
SlnDir: C:\Users\NickAc\Source\Repos\WinTabby\.\
DxpTarget: tools\net.r_eg.DllExport.targets
MsgGuiLevel: -1
LockIfError: The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Users\NickAc\Source\Repos\WinTabby\WinTabby.Hook\WinTabby.Hook.csproj
```

Demo Project files / Samples / etc.:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
</Project>
```

**Comment by 3F** [comment]
Thanks for the report,

Do you only have a preview release from 16.x ? and seems like stable in 15.x
Can you show result for the command:

> [hMSBuild](https://github.com/3F/hMSBuild/releases/download/v2.3/hMSBuild.bat) -only-path -vsw-as "-products * -latest -prerelease"

**Comment by NickAcPT** [comment]
Pardon for the late reply!

Here's the output:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\amd64\MSBuild.exe
```

I've also had this problem (not sure if related):
```
Could not load SDK Resolver. A manifest file exists, but the path to the SDK Resolver DLL file could not be found. Manifest file path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\SdkResolvers\Microsoft.Build.NuGetSdkResolver\Microsoft.Build.NuGetSdkResolver.xml'. SDK resolver path: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\Microsoft.Build.NuGetSdkResolver.dll  C:\Users\NickAc\Source\Repos\WinTabby\WinTabby\WinTabby.csproj
```
I've changed the xml file to the following as a workaround:

```xml
<SdkResolver>
  <Path>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\Microsoft.Build.NuGetSdkResolver.dll</Path>
</SdkResolver>
```

**Comment by NickAcPT** [comment]
I guess I could try reinstalling both Buildtools?

**Comment by 3F** [comment]
> Pardon for the late reply!

Don't worry, this was actually fast :) 

Since -prerelease indicates the same result, could you please also check this command:

```
hMSBuild -only-path -vsw-as "-products * -latest -prerelease -all"
```

> I guess I could try reinstalling both Buildtools?

Hmm, it could be really similar to recent problem: https://github.com/3F/DllExport/issues/139#issuecomment-604426500

**Comment by NickAcPT** [comment]
Didn't mean to close it. Is my installation somehow broken?
I've had VS 2017 installed before.

**Comment by NickAcPT** [comment]
> Are you sure that `hMSBuild -only-path -vsw-as "-products * -latest -prerelease"` returns VS2017 ? :) strange result
Yup. Don't know why
> ```
> vswhere -requires Microsoft.Component.MSBuild -products * -latest -prerelease
> ```
[out1.txt](https://github.com/3F/DllExport/files/4411933/out1.txt)

> ```
> vswhere -requires Microsoft.Component.MSBuild -products * -latest -prerelease -all
> ```
[out2.txt](https://github.com/3F/DllExport/files/4411935/out2.txt)

**Comment by 3F** [comment]
what about this:

```
hMSBuild -only-path -vsw-as "-products * -latest -prerelease" -vsw-version 2.7.1 -no-cache
```

**Comment by NickAcPT** [comment]
Only this:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\amd64\MSBuild.exe
```

**Comment by 3F** [comment]
And please this:

```
hMSBuild -debug -only-path -vsw-as "-products * -latest -prerelease"
```

```
hMSBuild -debug -only-path -vsw-as "-products * -latest -prerelease" -vsw-version 2.8.4 -no-cache
```

**Comment by NickAcPT** [comment]
Sorry again for the late reply.. Closed the tab accidentally.
> ```
> hMSBuild -debug -only-path -vsw-as "-products * -latest -prerelease"
> ```

<details>
<summary>Output</summary>
```
[ 0:55:26.58 ] trying via vswhere...
[ 0:55:26.58 ] bat/exe:  D:\Downloads\vswhere
[ 0:55:26.60 ] bat/exe:  C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere
[ 0:55:26.60 ] vswbin:  "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
[ 0:55:26.61 ] assign command:  -products * -latest -prerelease
[ 0:55:26.61 ] attempts with filter:
[ 0:55:26.74 ] vspath:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
[ 0:55:26.74 ] vsver:  16.6.29911.98
[ 0:55:26.75 ] found path via vswhere:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin
[ 0:55:26.75 ] found /amd64
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\amd64\MSBuild.exe
```
</details>

 
> ```
> hMSBuild -debug -only-path -vsw-as "-products * -latest -prerelease" -vsw-version 2.8.4 -no-cache
> ```

<details>
<summary>Output</summary>
```
[ 0:56:25.21 ] selected vswhere version: 2.8.4
[ 0:56:25.22 ] trying via vswhere...
[ 0:56:25.23 ] tvswhere:  C:\Users\NickAc\AppData\Local\Temp\hMSBuild_vswhere\_mta\1833130727vswhere
[ 0:56:25.23 ] GetNuTool call:  /p:ngpackages="vswhere/2.8.4:vswhere" /p:ngpath="C:\Users\NickAc\AppData\Local\Temp\hMSBuild_vswhere\_mta\1833130727vswhere"

  GetNuTool 1.8.0.7195+df76082
  (c) 2015-2018,2020  Denis Kuzmin [ x-3F@outlook.com ] GitHub/3F

Getting `vswhere/2.8.4` ... Extracting into "C:\Users\NickAc\AppData\Local\Temp\hMSBuild_vswhere\_mta\1833130727vswhere\vswhere"
[ 0:56:27.69 ] bat/exe:  C:\Users\NickAc\AppData\Local\Temp\hMSBuild_vswhere\_mta\1833130727vswhere\vswhere\tools\vswhere
[ 0:56:27.69 ] vswbin:  "C:\Users\NickAc\AppData\Local\Temp\hMSBuild_vswhere\_mta\1833130727vswhere\vswhere\tools\vswhere.exe"
[ 0:56:27.70 ] assign command:  -products * -latest -prerelease
[ 0:56:27.70 ] attempts with filter:
[ 0:56:27.80 ] vspath:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
[ 0:56:27.80 ] vsver:  16.6.29911.98
[ 0:56:27.81 ] found path via vswhere:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin
[ 0:56:27.81 ] found /amd64
[ 0:56:27.82 ] reset vswhere  C:\Users\NickAc\AppData\Local\Temp\hMSBuild_vswhere\_mta\1833130727vswhere
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\amd64\MSBuild.exe
```
</details>

**Comment by 3F** [comment]
The results confuses me a bit. Thank you for the new details!

Before your last reply I thought about bug or changed behavior of the vswhere tool between local and remote versions.

But the default command for hmsbuild points exactly on local use:

> [ 0:55:26.60 ] vswbin:  "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"

Where used 2.7.1 due to result from https://github.com/3F/DllExport/issues/143#issuecomment-606931074

But other forcibly use of 2.8.4 is also detects 16.6.29911.98

Can you please try again for this [first command](https://github.com/3F/DllExport/issues/143#issuecomment-606885698):

```
hMSBuild -only-path -vsw-as "-products * -latest -prerelease"
```

If still, then I will look later problems as part of the hMSBuild project.

For DllExport project more like we need add `-prerelease` key anyway. For the cases like yours it could be a good solution before replacing msbuild evaluator in future.

**Comment by NickAcPT** [comment]
> Can you please try again for this [first command](https://github.com/3F/DllExport/issues/143#issuecomment-606885698):
> 
> ```
> hMSBuild -only-path -vsw-as "-products * -latest -prerelease"
> ```
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\amd64\MSBuild.exe
```

So, did I somehow break your project? Am a bit confused. Also, I've updated the 2017 Build Tools but forgot to add that to one of my previous replies.

**Comment by NickAcPT** [comment]
I've opened DllExport and on the data tab there's this:

<details>
<summary>Data</summary>

```
Installed: False
Project type: Cs
PkgVer: 1.7.0
Storage: ProjectFiles
Compiler.Platform: Auto
Compiler.ordinalsBase: 1
Compiler.rSysObj: False
Compiler.ourILAsm: False
Compiler.customILAsm: 
Compiler.genExpLib: False
Compiler.peCheck: PeIl
Compiler.patches: None
SignAssembly: 
Identifier: B4A6A735-2150-4F7C-921C-0AE0828EDC6B
Instance: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\amd64\MSBuild.exe
Project path: 
Action: Configure
PlatformTarget: 
TargetFramework: 
TargetFrameworks: 
TargetFrameworkVersion: 
RootNamespace: 
AssemblyName: 
MgrArgs: 
MetaLib: tools\raw\lib\net20\DllExport.dll
MetaCor: tools\raw\lib\netstd\DllExport.dll
Proxy: 
StoragePath: .net.dllexport.targets
ddNS: 
ddNS max buffer: 500
UseCecil: True
intermediateFiles: False
timeout: 30000
RootPath: C:\Users\NickAc\Source\Repos\WinTabby\
PkgPath: C:\Users\NickAc\Source\Repos\WinTabby\packages\\DllExport.1.7.0\
SlnFile: 
SlnDir: C:\Users\NickAc\Source\Repos\WinTabby\.\
DxpTarget: tools\net.r_eg.DllExport.targets
MsgGuiLevel: -1
LockIfError: The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Users\NickAc\Source\Repos\WinTabby\WinTabby.Hook\WinTabby.Hook.csproj
```


</details>

**Comment by 3F** [comment]
> So, did I somehow break your project? 

No, I meant the bug that should be considered as part of other project. DllExport includes hMSBuild but this are different projects of course

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\amd64\MSBuild.exe

This is other result from your [first reply](https://github.com/3F/DllExport/issues/143#issuecomment-606905981):

> C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\amd64\MSBuild.exe

And it's more like this is what we need. Later I'll push solution with -prerelease key.

> If needed, I could try using a normal .NET Framework project for this.

No, it does not related to netfx.

**Comment by NickAcPT** [comment]
Oh I see. Thanks a lot for your time!
Is there anything needed from my side?

**Comment by 3F** [comment]
@NickAcPT Yes, please confirm solution 003360a4
compiled DllExport.bat: https://ci.appveyor.com/api/buildjobs/1992r7x51dcg5hx8/artifacts/bin%2FRelease%2FDllExport.bat

**Comment by NickAcPT** [comment]
Pardon the delay, but I can confirm that it just works. Thanks a lot.
Is there anything else needed for this issue or can it be closed?

**Comment by 3F** [comment]
> Pardon the delay, but I can confirm that it just works. Thanks a lot.

Good!

> Is there anything else needed for this issue or can it be closed?

I don't think so :) You can close it if your problem is fixed now. Or it will be closed anyway after merging into master branch.

@NickAcPT I don't have ETA yet for the new public release. I think we'll wait a bit to review the problem #141 and related. But you can use this CI build as a **temporary** solution in your case. Please don't use it in production before official release.

**Comment by NickAcPT** [comment]
> I don't think so :) You can close it if your problem is fixed now. Or it will be closed anyway after merging into master branch.

I'll leave this opened until the PR gets merged so that it's easier to know what's been fixed and what wasn't.

> But you can use this CI build as a **temporary** solution in your case. Please don't use it in production before official release.

Will do! Thanks a lot for helping 👍

**Comment by 3F** [comment]
FYI: corrected processing of -msb key after last fixes for this problem. Use 848e19b instead.
