### ISSUE TITLE
Set "Inherited = false" in AttributeUsage for DllExportAttribute

### ISSUE THREAD

**Issue by OmegaExtern** [3F/DllExport#15]
```
[AttributeUsage(AttributeTargets.Method/*, AllowMultiple = false*/, Inherited = false)]
public sealed class DllExportAttribute : Attribute
```

For more information, see this [page](https://msdn.microsoft.com/en-us/library/system.attributeusageattribute.inherited(v=vs.110).aspx).

**Comment by 3F** [comment]
How about a pull-requests ?

The current DllExport is not priority for me ([support for roslyn](https://github.com/3F/DllExport/issues/4) - yes !), 

I will do something from current tasks, but guys, **please support it with me** ! even if I can, I have no time for all :(

**Comment by 3F** [comment]
added with #16
