### ISSUE TITLE
Problem with windows 10

### ISSUE THREAD

**Issue by TERMI80** [3F/DllExport#162]
i try to compile my program in windows 10 and i always got this error.
I used Visual studio 2019 and 2017.
i uninstalled and installed package but i got always this error:

1>C:\Users\david\source\repos\RoyalBot_Mandatory\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error : Microsoft.Build.Utilities.ToolLocationHelper could not find ildasm.exe.
========== Ricompilazione: 1 completate, 0 non riuscite, 0 ignorate ==========

**Comment by 3F** [comment]
duplicate of #103
