### ISSUE TITLE
How to use this project in C#

### ISSUE THREAD

**Issue by jostartheworld** [3F/DllExport#163]
Hello,
I have been using this 
RGiesecke.DllExport.Metadata.dll for a couple years to export c# dll to work as c++ dll plugin but now it would not work on windows10 as it try to find some crt.dll missing.

Could you suggest how your project would help me replace RGiesecke.DllExport.Metadata.dll?
I am quite newbies in c++.
Thanks

-----------

*(Remove this section after reading. Click `Preview` tab for convenience)*

## ! Important

1. **Please** use our [wiki](https://github.com/3F/DllExport/wiki) first. +Available [**Q&A** list](https://github.com/3F/DllExport/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion).

2. Please try to use MSDN, stackoverflow, and other relevant places for understanding common practice with P/Invoke, scalar & unmanaged native types, marshaling, .net-domains, multithreading, ... ~something other. Because this is not directly related to our project to teach you programming. We can try to help you anyway, but please have a *conscience.*

### If you're ready to ask something

1. **Try to use** only [GitHub for your attachments and screenshots](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) instead of other places. It's free, it's enough.
2. **Do not** put inside message any very long text data ( ~ 10 Kb+ time for attachments ). Means only as file (text-based, or zip, etc). Because we're receiving this notification through email, so it's really ... [100K+](https://github.com/3F/DllExport/issues/71)
3. Please try to use [**basic formatting**](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to avoid code dancing 🕺 across the page.

**Comment by 3F** [comment]
@jostartheworld 

First of all, I'm sorry, but you need to learn to read. An *'Remove this section after reading'* just **confirms** that you didn't read anything.

Secondly,
Please start **here:** https://github.com/3F/DllExport/wiki/Quick-start
And, wiki at all: https://github.com/3F/DllExport/wiki

I believe this will help to remove a lot of questions.

Thirdly,
If you **still have the problem,** please follow [bug_report](https://github.com/3F/DllExport/issues/new?labels=bug&template=bug_report.md) template.

Thanks!

**Comment by 3F** [comment]
*closed because nothing is clear at all*
