### ISSUE TITLE
Error while building solution

### ISSUE THREAD

**Issue by TatiEgorova** [3F/DllExport#172]
I create UWP class library. 
And after building solution I get an error:
Microsoft.Build.Utilities.ToolLocationHelper could not find ildasm.exe.	

 **Version DllExport 1.5.2 was OK**

The question is related to: DllExport -version 1.7.3

**Comment by TatiEgorova** [comment]
C#
Visual Studio 2019

**Comment by 3F** [comment]
@TatiEgorova Please follow the bug issue template. I personally cannot say anything specific without the requested information. Thanks.

**Comment by 3F** [comment]
Closed due to inactivity.
