### ISSUE TITLE
ILMerge operation

### ISSUE THREAD

**Issue by JackKuo-tw** [3F/DllExport#182]
Hi,

I'm unable to merge my dll `EZreceiptDll2.dll` with `Newtonsoft.Json.dll`.
Is there any detail I missed? 

Here is my options:

![Screen Shot 2021-01-08 at 4 45 25 PM](https://user-images.githubusercontent.com/21074047/103994359-de07cd00-51d1-11eb-85af-232f875b3ce3.png)

Here is my ILMerge configuration:
(BTW, I'm not very sure what to write down in this textarea)

![Screen Shot 2021-01-08 at 4 45 15 PM](https://user-images.githubusercontent.com/21074047/103994369-e06a2700-51d1-11eb-892f-d9434a60a0d2.png)

-----------

Information from `Data` tab:

```
Installed: True; 1.7.4+c1cc52f; invoked: 1.7.4
Project type: Cs
Storage: ProjectFiles
Compiler.Platform: x86
Compiler.ordinalsBase: 1
Compiler.rSysObj: False
Compiler.ourILAsm: False
Compiler.customILAsm: 
Compiler.genExpLib: False
Compiler.peCheck: PeIl
Compiler.patches: None
PreProc.Type: ILMerge, DebugInfo, IgnoreErr
PreProc.Cmd: Newtonsoft.Json.dll EZreceiptDll2.dll
PostProc.Type: Predefined, DependentX86X64, SeqDependentForSys
PostProc.ProcEnv: $(SolutionPath);$(MSBuildThisFileFullPath);TargetDir
PostProc.Cmd: ...
SignAssembly: 
Identifier: 5F0765BA-6964-4A7D-AC90-D7DD394FC718
Instance: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64\MSBuild.exe
Project path: C:\Users\jackkuo\Desktop\EZreceiptDll2\EZreceiptDll2.csproj
Action: Configure
PlatformTarget: x86
TargetFramework: 
TargetFrameworks: 
TargetFrameworkVersion: v4.7.2
RootNamespace: EZreceiptDll2
AssemblyName: EZreceiptDll2
MgrArgs: -action Configure
MetaLib: tools\raw\lib\net20\DllExport.dll
MetaCor: tools\raw\lib\netstd\DllExport.dll
Proxy: 
StoragePath: .net.dllexport.targets
ddNS: System.Runtime.InteropServices
ddNS max buffer: 500
UseCecil: True
intermediateFiles: False
timeout: 30000
Options: None
RootPath: C:\Users\jackkuo\Desktop\EZreceiptDll2\
PkgPath: C:\Users\jackkuo\Desktop\EZreceiptDll2\packages\\DllExport.1.7.4\
SlnFile: 
SlnDir: C:\Users\jackkuo\Desktop\EZreceiptDll2\
DxpTarget: tools\net.r_eg.DllExport.targets
MsgGuiLevel: -1
LockIfError: 
```

**Comment by 3F** [comment]
> I'm not very sure what to write down in this textarea

The list of modules (.exe, .dll) separated by a whitespace char to be merged with the main module in the selected *EZreceiptDll2* project.

For your case, only `Newtonsoft.Json.dll` is needed in this list. Remove `EZreceiptDll2.dll` then try again.

**Comment by JackKuo-tw** [comment]
Thanks for your explanation!

If I only write down `Newtonsoft.Json.dll`, it shows the error message while compiling:
```
C:\Users\jackkuo\Desktop\EZreceiptDll2\Class1.cs(16707566) : error : syntax error at token '-' in:     IL_0027:  ldc.r8     -inf	EZreceiptDll2			
```

But I'm pretty sure my code in `Class1.cs` is right. 🤔

**Comment by 3F** [comment]
> error : syntax error at token '-' in:     IL_0027:  ldc.r8     -inf

#128
Your case requires Inf/-Inf token patching. Activating the related option should help.

**Comment by JackKuo-tw** [comment]
@3F Thank you~  It works!
Sorry for not knowing how to find this problem via the keyword "inf".
This project is so nice and your reply is so fast 🥰

Although I've written a [Chinese post](https://jackkuo.org/post/unmanaged_dll_export/) about this 1 year ago, I think it's time to write a more detailed one to promote this project :)

**Comment by 3F** [comment]
> @3F Thank you~ It works!

Good! Nice to hear that everything works well

> This project is so nice and your reply is so fast 🥰

I am trying :) https://twitter.com/github3F/status/1343482999766200320

> Although I've written a Chinese post about this 1 year ago, I think it's time to write a more detailed one to promote this project :)

Thank you! This is a good article! 
Because sometimes I'm watching some really crazy instructions like *Install/Uninstall then again Install via NuGet* ([?](https://twitter.com/github3F/status/1142526859852288000)). I don't even know where this came from and why it was so hard to just click the .bat file (in 1.7 added automated execution of this .bat for nuget, and seems like it helps better than [popup warn in 1.6.x](https://www.youtube.com/watch?v=9bYgywZ9pPE)).

Thanks for your interest in my projects!
https://github.com/3F

**Comment by JackKuo-tw** [comment]
@3F 
Here is a new [step-by-step tutorial blog post](https://jackkuo.org/post/export_unmanaged_dll_from_csharp/) in Traditional Chinese. (maybe you could use Google Translate XD)
It's welcome to use my screenshot to write an English version ~

**Comment by 3F** [comment]
@JackKuo-tw 

Good! Just a few clarifications:

* `.\DllExport.bat -action Configure` the *Configure* is the default action for 1.6.3+ thus it can be simply omitted. Other commands [here](https://github.com/3F/DllExport/wiki/DllExport-Manager#basic-commands)

* Some specific [namespace](https://github.com/3F/DllExport/wiki/Quick-start#namespaces) is [**not required**](https://github.com/3F/DllExport/issues/168#issuecomment-662988908). I don't know Chinese but it was translated as "2. Select the corresponding Namespace and use it here ... (need to be introduced separately)"

You can also point to the following important places:

* First steps (C#, VB, F#) - https://github.com/3F/DllExport/wiki/Quick-start
* Project example (source code C++, C#, VB) - https://github.com/3F/Examples/tree/master/DllExport/BasicExport
  for Java, yet only [screencast](https://www.youtube.com/watch?v=QXMj9-8XJnY&t=1367s);
  btw, we need to upgrade it to 1.7.4
  
And welcome if you want push some example for python, here https://github.com/3F/Examples/tree/master/DllExport/

Thanks!

**Comment by JackKuo-tw** [comment]
> the Configure is the default action for 1.6.3+ thus it can be simply omitted. Other commands here.

Thanks! It's helpful.

> Also, some specific namespace is not required. I don't know Chinese but it was translated as

You're so patient that really use the translation tool to read my blog 😇

Ok, I understand the `namespace` & `Interop` concepts after reading Microsoft docs. (newbie in Window dev)

In my observation, the options contain only 1 namespace and other DllExport built-in namespace, even if there is more than 1 namespace in the project. Is it a bug?

> You can also point to the following important places

No problem! The next version must attach it!

> And welcome if you want to push some example for Python

Sure, I'm still figuring out how to use `ctypes` lib.

---

Actually, there are so many programmers not familiar with English in Taiwan & China, especially those who are 40+ y.o.

I hope my blog can help them to develop more powerful & secure software, even if I'm not in the desktop application development industry (cloud instead).

Thank you very much!

**Comment by 3F** [comment]
> Ok, I understand the namespace & Interop concepts after reading Microsoft docs. (newbie in Window dev)

Wait, I meant only DllExport project. This is specific to its injection and more. While the namespaces are the common practice in many other programming languages just to isolate your space.

It can be also [empty to expose the feature using global namespace](https://github.com/3F/DllExport/issues/47#issuecomment-320778983). And [unicode support starting with 1.6.3](https://github.com/3F/DllExport/issues/80#issuecomment-495005854)

> In my observation, the options contain only 1 namespace and other DllExport built-in namespace, even if there is more than 1 namespace in the project. Is it a bug?

No. I think you don't need to change anything if you're not sure what to do with it.

> Sure, I'm still figuring out how to use ctypes lib.

Use my old example here https://github.com/3F/regXwild/issues/6#issuecomment-647149786

> I hope my blog can help them to develop more powerful & secure software, even if I'm not in the desktop application development industry (cloud instead).

Wish you success!
