### ISSUE TITLE
Dll by cmake with DllExport does not work in another application

### ISSUE THREAD

**Issue by Bogdan029** [3F/DllExport#185]
. . .

The question is related to:

* `DllExport -1.7.4`:
* Copy-paste from `Data` tab:

-----------

I want to create dll of my c# project with DllExport by cmake for use in another app(java), but I collided wit problem, app with the dll that I created by VS2019, works Ok, but with the dll that was created by cmake (using commands: "cmake . -B build/ -A x64" and "cmake --build build/) does not work (just crash). Could anybody help me?

CMakeList.txt my cmake file for main project
CMakeList1.txt my cmake file for subproject

[CMakeLists.txt](https://github.com/3F/DllExport/files/6070483/CMakeLists.txt)
[CMakeLists1.txt](https://github.com/3F/DllExport/files/6070484/CMakeLists1.txt)

**Comment by 3F** [comment]
@Bogdan029 Your CMakeLists are empty. I only found this 

> set_property(TARGET ${PROJECT_NAME} PROPERTY VS_DOTNET_REFERENCE_DllExport
    ${CMAKE_INSTALL_EXPORT_DIR}DllExport.1.7.4/gcache/metalib/C__.Wrapper/DllExport.dll)

that won't do anything at all

Convert also this:

* https://github.com/3F/Examples/blob/93618dc77bf53ba900b6fb077464b07790712ee8/DllExport/BasicExport/ClassLibrary1/ClassLibrary1.csproj#L90-L99

* https://github.com/3F/Examples/blob/93618dc77bf53ba900b6fb077464b07790712ee8/DllExport/BasicExport/ClassLibrary1/ClassLibrary1.csproj#L53-L68

But for cmake I'd recommend [**.net.dllexport.targets**](https://github.com/3F/DllExport/wiki/DllExport-Manager#external-storage) an external storage (configure it using Data tab). 

*Some cmake examples are waiting for someone to finally add them [here](https://github.com/3F/Examples/tree/master/DllExport)*

**Comment by Bogdan029** [comment]
> @Bogdan029 Your CMakeLists are empty. I only found this
> 
> > set_property(TARGET ${PROJECT_NAME} PROPERTY VS_DOTNET_REFERENCE_DllExport
> > ${CMAKE_INSTALL_EXPORT_DIR}DllExport.1.7.4/gcache/metalib/C__.Wrapper/DllExport.dll)
> 
> that won't do anything at all
> 
> Convert also this:
> 
> * https://github.com/3F/Examples/blob/93618dc77bf53ba900b6fb077464b07790712ee8/DllExport/BasicExport/ClassLibrary1/ClassLibrary1.csproj#L90-L99
> * https://github.com/3F/Examples/blob/93618dc77bf53ba900b6fb077464b07790712ee8/DllExport/BasicExport/ClassLibrary1/ClassLibrary1.csproj#L53-L68
> 
I don't have enough experience with cmake, so could you please, say me, how I should change my CMakeList?

**Comment by Bogdan029** [comment]
@3F  Thanks a lot.
