### ISSUE TITLE
How to use array/buffers

### ISSUE THREAD

**Issue by demiantres** [3F/DllExport#201]
Hi,

I have been using DllExport for simple functions for a while. It works great!
```
//C#
[DllExport]
public static int add(int a, int b)
{
    return a + b;
}

//C++
typedef int(__cdecl *add)(int a, int b);
auto fncAdd = (add)GetProcAddress(lib, "add");
int c = fncAdd(5, 7);
std::cout << c;
```

But how can I use DllExport with arrays? For instance:
```
//C#
[DllExport]
public static byte[] byteTest(byte[] dataIn)
{
	// do something with dataIn
	byte[] dataOut = new byte[100];
	return dataOut;
}

[DllExport]
public static string[] stringArrayTest(string[] dataIn)
{
	// do something with dataIn
	string[] dataOut = new string[100];
	return dataOut;
}

[DllExport]
public static int[] stringArrayTest(int[] dataIn)
{
	// do something with dataIn
	int[] dataOut = new int[100];
	return dataOut;
}
```

Can you point me to the correct place in the documentation or to an example?

Regards,

**Comment by 3F** [comment]
Hello,

> Can you point me to the correct place in the documentation or to an example?

* [Between unmanaged C++ / C# / Java /... Complex types and Strings. [Part-2]](https://github.com/3F/DllExport/wiki/Examples-Part-2)
* [About data types](https://github.com/3F/DllExport/wiki/Quick-start#about-data-types)

**Comment by 3F** [comment]
For *Conari* you can also use *NativeArray\<T\>*(it should be suitable since its implements *IMarshalableGeneric* interface) but seems I forgot to mention it in [other wiki](https://github.com/3F/Conari/wiki/Quick-start) and apparently not included in the [BindingContextTest](https://github.com/3F/Conari/blob/master/ConariTest/BindingContextTest.cs), only [basic](https://github.com/3F/Conari/blob/master/ConariTest/Types/NativeArrayTest.cs), don't remember why ... hmm

**Comment by demiantres** [comment]
Thanks! Using Marshall.copy works great in both ways (in and out of C#) without having to use Conari: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.copy?view=net-6.0

**Comment by mea05pb** [comment]
Hi, sorry to reopen this question but I am struggling with sending array from C# -> C++, using Marshal.Copy
in C# i have:
[DllExport]
public static IntPtr getArray()
        {
            IntPtr ptr = IntPtr.Zero;
           ptr =Marshal.AllocHGlobal(arr.Length*sizeof(float));
            Marshal.Copy(arr, 0, ptr, arr.Length);
            return ptr;
        }
and then in C++

	typedef float* (__cdecl* getArray)();
	float arr[4];
	void * arrptr = (void *) & arr;
    auto pGetArray = (getArray)GetProcAddress(lib, "getArray");
    arrptr = pGetArray();

What am I doing wrong?
