### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by CoenraadS** [3F/DllExport#204]
Hello

Apologies for yet another issue, I did search first but didn't see this one yet.
Closest I found was https://github.com/3F/DllExport/issues/164 but it's not my problem
Maybe related to https://github.com/3F/coreclr/issues/3?
. . .

The question is related to:

* `DllExport -version`:1.7.4
* Copy-paste from `Data` tab:
```
Installed: True; 1.7.4+c1cc52f; invoked: 1.7.4
Project type: CsSdk
Storage: ProjectFiles
Compiler.Platform: Auto
Compiler.ordinalsBase: 1
Compiler.rSysObj: False
Compiler.ourILAsm: False
Compiler.customILAsm: 
Compiler.genExpLib: False
Compiler.peCheck: PeIl
Compiler.patches: None
PreProc.Type: None
PreProc.Cmd: 
PostProc.Type: None
PostProc.ProcEnv: $(SolutionPath);$(MSBuildThisFileFullPath)
PostProc.Cmd: 
SignAssembly: 
Identifier: 9CDCCAD3-44FB-4AB5-89DD-73FF014FFD47
Instance: C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\MSBuild.exe
Project path: C:\Users\asdf\Documents\Projects\asdf\asdf\Installer\Dotnet\Dotnet\Dotnet.csproj
Action: Configure
PlatformTarget: x86
TargetFramework: net472
TargetFrameworks: 
TargetFrameworkVersion: 
RootNamespace: Installer.Dotnet
AssemblyName: 
MgrArgs: 
MetaLib: tools\raw\lib\net20\DllExport.dll
MetaCor: tools\raw\lib\netstd\DllExport.dll
Proxy: 
StoragePath: .net.dllexport.targets
ddNS: Installer.Dotnet
ddNS max buffer: 500
UseCecil: True
intermediateFiles: True
timeout: 30000
Options: None
RootPath: C:\Users\asdf\Documents\Projects\asdf\asdf\Installer\Dotnet\
PkgPath: C:\Users\asdfDocuments\Projects\asdf\asdf\Installer\Dotnet\packages\\DllExport.1.7.4\
SlnFile: 
SlnDir: C:\Users\asdfDocuments\Projects\asdf\asdf\Installer\Dotnet\
DxpTarget: tools\net.r_eg.DllExport.targets
MsgGuiLevel: -1
LockIfError: 
```

-----------

Hi

When I try to debug my project with `DLLExport` function from a unit-test, Visual Studio asks me to locate the `{projectName}.il` file?

Any idea how I can resolve this?

**Comment by 3F** [comment]
```
Compiler.rSysObj: False
Compiler.ourILAsm: False
Compiler.customILAsm: 
...
TargetFramework: net472
```

No, this is not related to https://github.com/3F/coreclr/issues/3

Did you try to set debugger type at least to Mixed? You can also note this in my old screencasts on youtube

Also make sure .pdb is located near final/modified assembly. That is, same to $(TargetDir) because of selected *x86* but $(TargetDir)\x86 for *x86+x64*

**Comment by CoenraadS** [comment]
Hi, when I remove the nuget package it debugs normally hence I think it's
related. Dll and pdb are in same folder, but the error isn't that it can't
find the pdb. Not really sure what else I can try to debug this issues

**Comment by 3F** [comment]
Hi, @CoenraadS

Can you clarify the following,

1. Where is entry point for both cases? From unmanaged/native side?
2. What actual value for debugger type?
3. Can you also reproduce this behavior from scratch in empty project?
4. Please attach build log if possible
 
Thanks

**Comment by CoenraadS** [comment]
Hi, so I have enabled mixed-mode debugged on both my project and the unit test project, to no avail. 

1. EntryPoint is from managed unit-test, then calling (still managed), a function with [DLLExport] defined. When I try to step into the function is asks for this .il file.

2. This is no value? I did not manage to step into the function

3. I attached empty project, just try to step into the function from the test project
[ClassLibrary1.zip](https://github.com/3F/DllExport/files/8104645/ClassLibrary1.zip)

**Comment by 3F** [comment]
Looks like a bug for x86 configurations.

Meanwhile this works well for "x86+x64". Check this out.

> This is no value?

My mistake, my thoughts were about C++ projects ~

![cpp](https://user-images.githubusercontent.com/3246589/154949360-5bc0245b-b43d-4499-818b-8af28411ce88.png)

**Comment by CoenraadS** [comment]
Do you mean change `PlatformTarget` from `x86` to `AnyCPU`?

Unfortunately I am interfacing with a 32 bit application and then the bindings break.

**Comment by 3F** [comment]
No. It will just produce both x86 and x64 modules in individual folders (i.e. $(TargetDir)\x86 and $(TargetDir)\x64).
There is nothing incompatible for your task. You need only select "x86+x64" when configuring, then Apply. It should help until fix.

**Comment by CoenraadS** [comment]
Thanks for your patience, it is working now.

**Comment by 3F** [comment]
> at least from the unit test

Can you describe steps for a "remote-debug situation" because "x86+x64" should work for other cases too, like manual attaching to process (just checked it) for debugger or other entering from some executable modules.

**Comment by CoenraadS** [comment]
[InnoSetupExample.zip](https://github.com/3F/DllExport/files/8148354/InnoSetupExample.zip)

Hi, I think it's easiest to reproduce using the situation I am facing, running from InnoSetup

To reproduce, install InnoSetup

Then run the attached file at: ClassLibrary1\bin\Debug\net472\win-x86\x86

It will automatically try to launch the debugger, giving the `.il` error

**Comment by CoenraadS** [comment]
[InnoSetupExample (2).zip](https://github.com/3F/DllExport/files/8148389/InnoSetupExample.2.zip)

`ClassLibrary1\bin\Debug\net472\win-x86\x86\CodeDll.iss`

Hi, I think the easiest way to reproduce is to run it from [InnoSetup](https://jrsoftware.org/isdl.php)

I made a minimal example, just run the script from InnoSetup and it will automatically launch the debugger and give the `.il` error
