### ISSUE TITLE
DllExport does not work with Visual Studio 2019.   

### ISSUE THREAD

**Issue by gkgg27** [3F/DllExport#208]
Any help is much appreciated in solving the below listed two errors!

I have attached my Sample project to simulate the errors.
[TestDllExport.zip](https://github.com/3F/DllExport/files/8430143/TestDllExport.zip)

Steps to reproduce:
1. Create a sample VB.NET class library project in VS 2017 and add a module as shown below. 
Imports System.Runtime.InteropServices

Public Module TestExcelMacros

    <DllExport(CallingConvention:=CallingConvention.StdCall)>
    Public Sub DisplayHello(myName As String)
        MsgBox("Hello" & myName)
    End Sub

    <DllExport(CallingConvention:=CallingConvention.StdCall)>
    Public Function DisplayString() As String
        Dim testDbl As Double
        testDbl = Double.NaN
        Return "Gayathri"
    End Function

    <DllExport(CallingConvention:=CallingConvention.StdCall)>
    Public Function DisplayNumber() As Double
        Return 123.123
    End Function

End Module

When I use the dll in Excel macro excel generates the error Can't find entry point in dll.

2. Next when I open the attached sample project in VS 2017 there are no compile time errors. But when I open the solution in VS 2019 it generates the error
C:\Users\ro531f\source\repos\TestDllExport\TestDllExport\TestExcelMacros.vb(13) : error : syntax error at token '-' in:     IL_0001:  ldc.r8     -nan(ind)	TestDllExport	C:\Users\ro531f\source\repos\TestDllExport\packages\DllExport.1.7.4\tools\net.r_eg.DllExport.targets	76	

You can find the net.r_eg.DllExport.targets file inside the Zip file.

**Comment by 3F** [comment]
Hello,

> Compiler.patches: None

Try with `-nan(ind)` option. Or try with other supported IL assembler, see related options when configuring.

**Comment by gkgg27** [comment]
> Hello,
> 
> > Compiler.patches: None
> 
> Try with `-nan(ind)` option. Or try with other supported IL assembler, see related options when configuring.

Thank you for the reply! 
I used the IL assembler from the DLLExport packages folder and the error does not occur anymore.

**Comment by 3F** [comment]
Does this mean that -nan(ind) patch doesn't help? If so, I recommend following the bug report template.

> I used the IL assembler from the DLLExport packages folder

It sounds like setting the path manually... Just to be clear, we provide "use our assembler" option which does not require any path setting
________________________________

**Comment by gkgg27** [comment]
Sorry I did not explain clearly earlier, I did not set the path manually.  
While installing the DllExport nuget package I chose the option to use the provided IL assembler and the error went away.

**Comment by 3F** [comment]
I see. But I'm still not sure did you try to apply -nan(ind) patch together with original MS assembler? (checkbox below assemblers options)
I'm just trying to say, my IL assmelber has some extra features but also some limitations. So the trivial patching -nan(ind) might be the best way in your case
________________________________
