### ISSUE TITLE
Issues building thru TFS Build

### ISSUE THREAD

**Issue by nlz242** [3F/DllExport#21]
Building on my computer works fine, but i'm having a hard time building on my build server (TFS 2010).
Using msbuild tools 14.0, targetting .net 4.0. 
I get this error :
Sorry for the french-ish stacktrace

```
D:\Builds\35\MyProject\Sources\packages\DllExport.1.5.0\tools\net.r_eg.DllExport.targets(42,5): error :  [D:\Builds\35\MyProject\Sources\Client\Client.csproj]
     à RGiesecke.DllExport.Parsing.IlParser.RunIlTool(String installPath, String toolFileName, String requiredPaths, String workingDirectory, String settingsName, String arguments, String toolLoggingCode, String verboseLoggingCode, IDllExportNotifier notifier, Int32 timeout, Func`2 suppressErrorOutputLine) dans D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\Parsing\IlParser.cs:ligne 378
     à RGiesecke.DllExport.Parsing.IlDasm.Run() dans D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\Parsing\ILDasm.cs:ligne 22
     à RGiesecke.DllExport.DllExportWeaver.RunIlDasm(String tempDirectory) dans D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\DllExportWeaver.cs:ligne 188
     à RGiesecke.DllExport.DllExportWeaver.Run() dans D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\DllExportWeaver.cs:ligne 51
     à RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.Execute() dans D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:ligne 437
```

Any idea ?

**Comment by 3F** [comment]
seems `exitCode != 0` and in your stack trace I also see that's after IlDasm.Run()

So, what settings for this ? Is it our coreclr ?
you can also simply copy all properties of DllExport from your Client.csproj or attach this file if it's possible

Probably I need full log, you can set `detailed` or better `diagnostic` verbosity: `/verbosity:detailed` / `/verbosity:diagnostic` or `/v:d` /  `/v:diag`

But, if this problem with IL (like #17) I need also simple example to reproduce it, etc.

**Comment by nlz242** [comment]
I made a small project with only an Hello World type method.
If i build it on my computer, it works well, but my TF Build server has the same issue.
I included the Diagnostic log, the project and my TF Build template (which is the DefaultTemplate using Toolversion 14.0 & with a call to NuGet restore before build)
As for DllExport, the only option i changed form the default is selected the "x86" radio button instead of "x86+x64" or "x64"
Again, sorry for the french-ish log file.
[BuildTest.log.txt](https://github.com/3F/DllExport/files/580976/BuildTest.log.txt)
[BuildTest.zip](https://github.com/3F/DllExport/files/580978/BuildTest.zip)
[DefaultTemplateWithNuGet.xaml.txt](https://github.com/3F/DllExport/files/580981/DefaultTemplateWithNuGet.xaml.txt)

**Comment by 3F** [comment]
@nlz242 Thank you for details

> Again, sorry for the french-ish log file.

to build with eng. locale, you can use like this:

```bash
chcp 437
...
msbuild "YourProject.sln" /t:Build
```

Well, your problem from calling our ildasm.exe:

```
D:\Builds\34\1500-MUNIC\CI.Dev.TestBuild\Sources\packages\DllExport.1.5.0\tools\coreclr\ildasm.exe /quoteallnames /unicode /nobar /linenum "/out:C:\Users\TFSService\AppData\Local\Temp\tmp2DE8\BuildTest.il" "D:\Builds\34\1500-MUNIC\CI.Dev.TestBuild\Binaries\BuildTest.dll"
```

But you have no any message from this :( Later I'll try to reproduce this on some TFS.

You can also try to find this problem:

* Try manually call (before build) \packages\DllExport.1.5.0\tools\coreclr\ildasm.exe, to check that's problem not with dependencies or some restrictions for your TFS.
* And/or check with original coreclr. For v1.5 this `<DllExportOurILAsm>false</DllExportOurILAsm>` temporarily does not work (#20), thus:
    * use already fixed version from CI + DllExportOurILAsm as false: [DllExport.1.5.0.nupkg - build-36](https://ci.appveyor.com/api/buildjobs/h96ffmt6kd3asfjf/artifacts/bin%2FRelease%2FDllExport.1.5.0.nupkg)
    * or prev. v1.4 https://www.nuget.org/packages/DllExport/
    * or original UnmanagedExports: https://www.nuget.org/packages/UnmanagedExports/

**Comment by nlz242** [comment]
Well, that fixed it!

I tried to run ildasm manually and got a message saying it can't find api-ms-win-crt-string-l1-1-0.dll.
So i went ahead and installed the VC++ 2015 redist on my build server and now everything builds as it should, without errors! 

Thanks a ton for your help! :)

**Comment by 3F** [comment]
:)

Good !

> Thanks a ton for your help! :)

I'm glad that this helped you -_*

**Comment by 3F** [comment]
> VC++ 2015 redist

by the way yes, **anyone else, please note** that my coreclr version was compiled with 14.0

* https://ci.appveyor.com/project/3Fs/coreclr/build/build-11
