### ISSUE TITLE
Can not build ILAsm contain with declared DllImport (NET6)

### ISSUE THREAD

**Issue by Zeki-Gursoy** [3F/DllExport#211]
Error message:

"RunIlAsm: Something went wrong. We can't find '2' exports from PE32/PE32+ module **** net.r_eg.DllExport.targets	1

**Comment by 3F** [comment]
Hello,

The errors (+ #210) means that the expected entries in the export 
directory in your final module were not found for some reason.
This behavior is controlled by "PE Check" options, after 
https://github.com/3F/DllExport/issues/59#issuecomment-348702199

As a reason, I think this is related 
https://github.com/3F/DllExport/issues/209#issuecomment-1126045679

**Comment by 3F** [comment]
oops, "PE Check" impl was a little earlier than the mentioned src, i.e. 
https://github.com/3F/DllExport/issues/55#issuecomment-339989014

**Comment by 3F** [comment]
Closed due to inactivity. Please open it again if you still have problems or questions.

Generally it would be nice to see the reason for the missing functions in your module to make sure it's not a bug.
