### ISSUE TITLE
it not work :/

### ISSUE THREAD

**Issue by iocmet** [3F/DllExport#212]
The type or namespace name 'DllExport' could not be found (are you missing a using directive or an assembly reference?)

**Comment by 3F** [comment]
Hello,

Is there a reason why are you avoiding issue templates?

Please follow the bug template and provide required information about 
used versions etc.
I can't understand anything without it.

**Comment by 3F** [comment]
Closed due to lack of information. Please feel free to reopen or create a new one in order to add required minimal information. Thanks.
