### ISSUE TITLE
When open multiple c++ exe , the second exe fail to invoke c# dllexport function (the second exe crash when invoke)

### ISSUE THREAD

**Issue by wu162** [3F/DllExport#225]
Steps to reproduce:

. . .

* `DllExport -version`: 1.7.4
* Used Visual Studio / MSBuild / ...: Visual Studio 2022

Information from `Data` tab or log data: 

. . . [{attachment if log}](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)

Demo Project files / Samples / etc.:

. . .

I create a c++ dll that use c# export function (the c++ dll is in import address table of c++ exe, the c# export dll is net framework4.5), when open a second exe and the c++ dll invoke c# export function, the second exe crash

**Comment by 3F** [comment]
Hello,

Unfortunately I don't understand the issue. Could you please clarify what you mean or how to reproduce the problem. Thanks.

**Comment by 3F** [comment]
Closed due to inactivity. Please provide further details if the problem still exists.
