### ISSUE TITLE
Not work, DllExport not found

### ISSUE THREAD

**Issue by neoedmund** [3F/DllExport#227]
Steps to reproduce:

. . .

* `DllExport -version`: 1.7.4
* Used Visual Studio / MSBuild / ...:  2022
using .Net6.0 , using NetCore2.2 is same
 
![dllexport1](https://github.com/3F/DllExport/assets/67332/7ea69011-f12a-4d75-8238-c6aef545fe5c)

**Comment by 3F** [comment]
Hello,
Please follow the issue template and provide related information. Without it the problem is unclear. Thanks.

**Comment by neoedmund** [comment]
nevermind, I found the best answer of 2023 https://github.com/dotnet/samples/tree/main/core/nativeaot/NativeLibrary

this lib seems outdated and buggy, so closing this issue
