### ISSUE TITLE
NET7 System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'

### ISSUE THREAD

**Issue by northstarvn** [3F/DllExport#228]
Steps to reproduce:

1. Create a solution with: C# console, C++ DLL, C# dll (for exports). All attached in zip
2. Test the C++ export OK
3. The C# dll export following guidance here [https://github.com/3F/DllExport/issues/130](url)  fails with SEH exception. Even a manual config of the testExport.csproj to x86 didn't help and produced the same problem.
4. Disassembly suggests the export entry doesn't point to function body

* `DllExport -version`:  1.7.4
* Used Visual Studio / MSBuild / ...: VS Community 2022 (64-bit) Version 17.6.2

[testDll.zip](https://github.com/3F/DllExport/files/13345754/testDll.zip)

**Comment by anonymousjaggu** [comment]
Hi @3F 

I am also facing the same issue, i have recently upgraded the projects to .net core `<TargetFramework>net8.0-windows</TargetFramework>` 

May i get some help on fixing the issue?

**Comment by 3F** [comment]
Hello. Thanks for the report!

.NET 8 & .NET 7 (@northstarvn's testDll.zip) are not supported at the moment and it was already discussed in previous issues.

My implantation is planned according to the new priorities described in my last [article](https://www.reddit.com/r/x3F/comments/189wi1h/first_public_release_this_year_and_something/)

Closed as duplicate #219
