### ISSUE TITLE
Provide support for building in Intellij Rider

### ISSUE THREAD

**Issue by bukowa** [3F/DllExport#229]
Follow up to https://github.com/3F/DllExport/issues/141#issuecomment-608103235

I just tried using DllExport for a simple task. Found the repository and while using Rider landed on this topic.
Building in Visual Studio just works. I have no idea what is really happening and what steps should one perform to investigate this topic because of my little to non knowledge about C# and build chains. Maybe someone can provide more context.

**Comment by 3F** [comment]
Hello,

Are there any problems using the [msbuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022#syntax) together with Intellij Rider? I think most modern IDEs provide options to build using msbuild, isn't it? it's important part of SDKs including *dotnet* etc.

As I voiced in #141

> Even officially they (*MS team) recommends to use exactly this instead of *dotnet build* for some related problems with tasks etc.

To build your [configured](https://github.com/3F/DllExport/wiki/Quick-start#configuring-the-projects) project, for example:

> "path to MSBuild.exe" /p:Configuration=Release

or using *hmsbuild* that helps with MSBuild tools

> [hmsbuild](https://github.com/3F/hMSBuild#-help) ~c Release

**Comment by bukowa** [comment]
> Hello,
> 
> Are there any problems using the [msbuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022#syntax) together with Intellij Rider? I think most modern IDEs provide options to build using msbuild, isn't it? it's important part of SDKs including _dotnet_ etc.
> 
> As I voiced in #141
> 
> > Even officially they (*MS team) recommends to use exactly this instead of _dotnet build_ for some related problems with tasks etc.
> 
> To build your [configured](https://github.com/3F/DllExport/wiki/Quick-start#configuring-the-projects) project, for example:
> 
> > "path to MSBuild.exe" /p:Configuration=Release
> 
> or using _hmsbuild_ that helps with MSBuild tools
> 
> > [hmsbuild](https://github.com/3F/hMSBuild#-help) ~c Release

Hey I am sorry but I don't longer remember anything about the topic.

**Comment by 3F** [comment]
I see. I'm closing the issue. Feel free to open a new one if you discover a new problem or question.
