### ISSUE TITLE
About RealTimeTelemetry

### ISSUE THREAD

**Issue by crazyGod666** [3F/DllExport#231]
I want to use your SDK to develop plugins (AddOns) about real-time telemetry. But I can't find the interface about real-time telemetry, have you provided the relevant interface? If yes, can you tell me the name of it?

**Comment by 3F** [comment]
Hello,

No. DllExport does not use or provide related interface because we do not collect telemetry and generally do not touch sensitive information from modified user's assemblies at all. It also be noted again that the final modified assemblies does not contain any references to DllExport tool

**Comment by 3F** [comment]
I close the issue. Please provide further details if the problem still exists.
