### ISSUE TITLE
Use a custom name with a mixture of Japanese and English, but do not display Japanese

### ISSUE THREAD

**Issue by crazyGod666** [3F/DllExport#233]
I have written an ACMI document, which includes the following content:
FileType=text/acmi/tacview
FileVersion=2.2
0,ReferenceTime=2011-06-02T05:00:00Z,Author=Au,Title=Tac_Task1
1,T=100|100|2000|0|||||,Name=A-7,Color=Red
2,T=100|100|2000,Name=A-7,Color=Blue,ShortName=TestNamesaサービス私dsaandName
#0
1,T=100.5|||0|0|0|40|40|90,Label=2
#20
1,T=101|100.5|,AOS=45,FocusedTarget=2,Radius=100
When I open it by Tacview,I can not see the object's total ShortName on label which the id is 2.
What is the reason?Should I add  Japanese font?

**Comment by crazyGod666** [comment]
![image](https://github.com/3F/DllExport/assets/141392814/c067d46b-8196-4b90-8ef9-9d9e517cce0b)
+

**Comment by 3F** [comment]
Hello,

Depends on how *ShortName* was marshaled in your code.
Have you seen https://github.com/3F/DllExport/wiki/Quick-start#about-data-types

For example, using [Conari](https://github.com/3F/Conari/wiki/Quick-start) you can access it through *TCharPtr* etc.

```csharp
[DllExport]
public static void init(TCharPtr shortName)
{
    if(shortName == "Achilles") ...
}
```

![TCharPtr_8_16bit](https://github.com/3F/DllExport/assets/3246589/30aecf9b-3b65-43e0-99f7-ea32979ff054)

```csharp
NativeString<TCharPtr> ns = new("Achilles");

TCharPtr.Unicode = true / false; // runtime -> WCharPtr / CharPtr
```

![TCharPtr_8_16bit_2](https://github.com/3F/DllExport/assets/3246589/c1e94a22-49fb-47a5-ab8d-f6dccc0b6dfd)

Please clarify the case.

**Comment by 3F** [comment]
Some new tests with Unicode can be found here:
* https://github.com/3F/DllExport/blob/master/src/DllExport/assets/NetfxAsset/Basic.cs
* https://github.com/3F/DllExport/blob/master/src/DllExport/UnitedTest/NetfxAssetBasicTest.cs

Let me know if there are still problems
