### ISSUE TITLE
Installing the NuGet package doesn't change any project references.

### ISSUE THREAD

**Issue by Arlen22** [3F/DllExport#234]
I don't know the first thing about the window that pops up when I install the NuGet package (other than I can get it to popup again by going into my solution and clicking a bat file, but then I have to select the solution manually). 

I don't know how to get it to add the project references to my existing projects. Clicking apply immediately does nothing, and clicking apply after checking "Installed" also does nothing. 

The question is related to:

* `DllExport -version`: v1.7.4.29858+c1cc52f
* Copy-paste from `Data` tab:

**Comment by 3F** [comment]
Hello,

> when I install the NuGet package

Please read [Configuring the projects](https://github.com/3F/DllExport/wiki/Quick-start#configuring-the-projects)

> [How to get DllExport](https://github.com/3F/DllExport?tab=readme-ov-file#how-to-get-dllexport)
> Since 1.6+ does not provide official support for **NuGet** [?], something somewhere **may not work or not work properly.**

And please provide information from the `Data` + attach *cfg.log* using command `DllExport >cfg.log` when applying settings.

> Clicking apply immediately does nothing, and clicking apply after checking "Installed" also does nothing.

> Copy-paste from Data tab:

**Comment by 3F** [comment]
Closed due to inactivity. Please open it again if you still have problems or questions.
