### ISSUE TITLE
Can I throw an exception?

### ISSUE THREAD

**Issue by Zeki-Gursoy** [3F/DllExport#237]
Yes, as I mentioned in the title, I want to throw an exception. However, the application crashes.

Is there a way to throw an exception without the application crashing? (Application's name is EXCEL.EXE)

Best regards,

**Comment by 3F** [comment]
Hello,
The crash is possible because the exception (CLR) is not actually caught in your excel VBA script (correct me what is used in your case).

Here I have already suggested something about the handling,
* #85
