### ISSUE TITLE
How to Call JNA to VB.net ByRef String Function

### ISSUE THREAD

**Issue by K-Full** [3F/DllExport#25]
I want to call vb.net ByRef and String function from java.
vb.net dll is maked by UnmanagedExports.

//java
String[] str = {"testJavaWrited"};
String[] str2 = {"testJavaWrited2"};
final VbWrapper wr = (VbWrapper)Native.loadLibrary("vbtestlib", VbWrapper.class);
wr.test(str,str2);
System.out.println(str); // not printed
System.out.println(str2); // not printed

// jna mapping
public interface VbWrapper extends Library {
    public int test(String[] str,String[] str2);
}

//vb.net
<DllExport("test", CallingConvention.StdCall)>
Function test(ByRef str As String, ByRef str2 As String) As Integer
    MsgBox("test Called")   ' printed
    MsgBox(str) ' printed
    str = "testStringWrited"
    str2 = "testStringWrited2"
    Return 0
End Function ' heap error

I need your help everybody.

http://stackoverflow.com/questions/41830352/how-to-call-jna-to-vb-net-byref-string-function

**Comment by 3F** [comment]
:) You should use pointer to allocated string.

For example:

```csharp
[DllExport]
public static int getStringArgs(ref IntPtr ptr)
{
    ptr = new UnmanagedString("Hello from .NET and Conari", UnmanagedString.SType.Ansi);    
    return 0;
}

[DllExport]
public static IntPtr getString()
{
    return new UnmanagedString("Hello from .NET and Conari", UnmanagedString.SType.Ansi);
}
```

**Java:**

```java
public interface CAPI extends Library
{
    public PointerByReference getString();
    public int getStringArgs(LongByReference ptr); // see also Pointer etc.
}
```

```java
CAPI l = Native.loadLibrary("DllExportAndJNA", CAPI.class);
...
LongByReference ptr = new LongByReference();
l.getStringArgs(ptr);
(new Pointer(ptr.getValue())).getString(0); // Hello from .NET and Conari
```

```java
PointerByReference pbr = l.getString();
pbr.getPointer().getString(0); // Hello from .NET and Conari
```

etc.
In example above, the UnmanagedString is part of [Conari engine](https://github.com/3F/Conari), but of course you can use anything else, just for sample

But anyway, **do not forget** deallocate all data from unmanaged memory !
And I recommend to use structures to aggregate all your states if you plan complex parameters between calling.

**Comment by K-Full** [comment]
Thank you very much Denis Kuzmin.
Your idea is good solution.
But, I wanted to use the standard library as much as possible.

Here is my vb code.

    [DllExport]
    public static int getStringArgs(ref IntPtr ptr)
    {
        ptr = Marshal.StringToCoTaskMemAnsi("Hello from .NET")
        return 0;
    }

    [DllExport]
    public static void freeString(ref IntPtr ptr)
    {
        Marshal.ZeroFreeCoTaskMemAnsi(ptr)
        return;
    }

Thank you for your help.
