### ISSUE TITLE
Failing to compile in VS 2017

### ISSUE THREAD

**Issue by equalitybots** [3F/DllExport#29]
When using C# 4.6 +

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		The "DllExportAppDomainIsolatedTask" task failed unexpectedly.
> System.ArgumentException: Requested value 'Version46' was not found.
> 
> Server stack trace: 
>    at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
>    at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
>    at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
>    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.<>c__DisplayClass126_0.<GetGetToolPathInternal>b__1(Version version, String toolName) in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 608
>    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.TryToGetToolDirForFxVersion(String toolFileName, Func`3 getToolPath, String& toolDirectory) in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 775
>    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateToolPath(String toolFileName, String currentValue, Func`3 getToolPath, String& foundPath) in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 756
>    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateFrameworkPath() in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 722
>    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateInputValues() in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 507
>    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.Execute() in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 410
>    at RGiesecke.DllExport.MSBuild.DllExportAppDomainIsolatedTask.Execute() in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\DllExportAppDomainIsolatedTask.cs:line 397
>    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
> 
> Exception rethrown at [0]: 
>    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    at Microsoft.Build.Framework.ITask.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	TestDll			
>

**Comment by 3F** [comment]
hmm, I see

**temporarily:**

try to install msbuild tools (~20 MB), for example:

* https://www.microsoft.com/en-us/download/details.aspx?id=48159

related: https://blogs.msdn.microsoft.com/vcblog/2016/11/16/introducing-the-visual-studio-build-tools/

**or** try to reduce version via `DllExportTargetFrameworkVersion`:

```xml
<DllExportTargetFrameworkVersion>v4.0</DllExportTargetFrameworkVersion> <!-- for dllexport -->
<TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion> <!-- for your project -->
```

**Comment by equalitybots** [comment]
Installing the msbuild tools solves the issue.

**Comment by 3F** [comment]
good !

please test also the latest changes (without described solutions above)
/build here: https://ci.appveyor.com/project/3Fs/dllexport/build/build-40/artifacts

**Comment by 3F** [comment]
This problem should be fixed in v1.5.2
Public build [v1.5.2.22710 [ 1f6b2d9 ]](https://www.nuget.org/api/v2/package/DllExport/1.5.2)

**Comment by bbday** [comment]
I think i have same issue with 4.7 target framework:

Error The "DllExportAppDomainIsolatedTask" task failed unexpectedly.
System.ArgumentException: Requested value 'Version47' was not found.

Server stack trace: 
   in System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   in System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   in System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   in RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.<>c__DisplayClass8.<GetGetToolPathInternal>b__7(Version version, String toolName) in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:riga 568
   in RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.TryToGetToolDirForFxVersion(String toolFileName, Func`3 getToolPath, String& toolDirectory) in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:riga 725
   in RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateToolPath(String toolFileName, String currentValue, Func`3 getToolPath, String& foundPath) in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:riga 698
   in RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateFrameworkPath() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:riga 680
   in RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateInputValues() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:riga 396
   in RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.Execute() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:riga 264
   in RGiesecke.DllExport.MSBuild.DllExportAppDomainIsolatedTask.Execute() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\DllExportAppDomainIsolatedTask.cs:riga 241
   in System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   in System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   in System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   in System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   in Microsoft.Build.Framework.ITask.Execute()
   in Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   in Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	EasyLoad

**Comment by 3F** [comment]
@bbday what version ? 

please check release-candidate 1.6-RC. 
I have no plan to support old 1.5.x.

**Comment by bbday** [comment]
I used nutget package 1.2.7 then i installed "build tool 2015" it worked

**Comment by 3F** [comment]
nice <_<

Our packages here: https://www.nuget.org/packages/DllExport/

* **Latest Release** via GitHub: https://github.com/3F/DllExport/releases/latest

* **[How to get](https://github.com/3F/DllExport#how-to-get-dllexport)**
    * [Latest manager](https://3f.github.io/DllExport/releases/latest/manager/)

**Comment by dagostinelli** [comment]
I have a freshly installed VS2017, all patches. I ran Update-Package -reinstall to make sure my packages were correct.  I'm on v1.2.7 of DllExport and when I build I get this:

```
The "DllExportAppDomainIsolatedTask" task failed unexpectedly.
System.ArgumentException: Requested value 'Version46' was not found.
```

This is the full error

```
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018: The "DllExportAppDomainIsolatedTask" task failed unexpectedly.
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018: System.ArgumentException: Requested value 'Version46' was not found.
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018: 
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018: Server stack trace: 
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.<>c__DisplayClass8.<GetGetToolPathInternal>b__7(Version version, String toolName) in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 568
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.TryToGetToolDirForFxVersion(String toolFileName, Func`3 getToolPath, String& toolDirectory) in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 725
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateToolPath(String toolFileName, String currentValue, Func`3 getToolPath, String& foundPath) in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 698
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateFrameworkPath() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 680
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateInputValues() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 396
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.Execute() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 264
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at RGiesecke.DllExport.MSBuild.DllExportAppDomainIsolatedTask.Execute() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\DllExportAppDomainIsolatedTask.cs:line 241
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018: 
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018: Exception rethrown at [0]: 
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at Microsoft.Build.Framework.ITask.Execute()
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\Users\User\source\repos\myapp\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

```

What worked for me was to lower my .NET version to v4.0 on just the assembly that uses DllExport.  

I happen to be able to do that in my case because of how I have things setup.  But, I imagine that this isn't going to be the case for everyone.  This is why I'm mentioning this.

**Comment by 3F** [comment]
> I'm on v1.2.7 
>> This is the full error
>>> 2>C:\Users\User\source\repos\myapp\packages\ **UnmanagedExports.1.2.7**

Guys ! **again**, our packages **here**: https://www.nuget.org/packages/DllExport/
* https://github.com/3F/DllExport/issues/29#issuecomment-349960803

### [Quick-start](https://github.com/3F/DllExport/wiki/Quick-start)
  * [How to (Screencast)](https://www.youtube.com/watch?v=sBWt-KdQtoc)

**Comment by dagostinelli** [comment]
Do you also own UnmanagedExports? (If so, maybe you could put a "this is deprecated, use this other one" message on the Nuget portal.

**Comment by 3F** [comment]
@dagostinelli I can only contact with Robert for this purpose. But I'm still not sure about his position because of latest discussion:

> oh, I will put it on github.
> You kinda force me to, which is a good thing.

Well, it was 2016.

**Comment by duzers** [comment]
I have this problems:
Error		The "DllExportAppDomainIsolatedTask" task could not be initialized with its input parameters.				
Error		The "VsDevCmd" parameter is not supported by the "DllExportAppDomainIsolatedTask" task. Verify the parameter exists on the task, and it is a settable public instance property.

**Comment by 3F** [comment]
I lock any conversation now for this issue because of still **mixed** questions and reports.

Please **[Open New Issue](https://github.com/3F/DllExport/issues/new)** about **specific** bugs or for some discussion.


@duzers

*versions, configuration, commands, project files, samples, log,* ... **anything** more about your problem. Thanks.

We can't help you just from this common message.
