### ISSUE TITLE
Post-Build event no longer work as expected (if compared to UnmanagedExports)

### ISSUE THREAD

**Issue by OmegaExtern** [3F/DllExport#35]
I have discovered this bug a while ago and I am surprised to see that it is still not fixed.
Note: **This bug is specific to DllExport code/package (any version)**! Such bug does not exist in [UnmanagedExports code/package (v1.2.7)](https://www.nuget.org/packages/UnmanagedExports).

For example:
1. Create a new C# class library project.
2. Download/Install DllExport into project via NuGet (`Install-Package DllExport`, pick **any version**, the newest release v1.5.2 is still affected by this bug).
3. Use whatever DllExport configuration options you want, it doesn't matter at all.
4. Go to Project -> Properties -> Build Events page.
5. Enter (or copy/paste) the following into post-build command line:
`COPY /Y "$(TargetPath)" "$(SolutionDir)$(TargetFileName)"`

You should have something like this:
![image](https://cloud.githubusercontent.com/assets/6441892/25709776/8742b55e-30ea-11e7-8f9e-114e5e4751df.png)
Next, build the project and wait for it to complete.
The above simple post-build event should **copy the compiled DLL with exports** into another directory (overwriting the existing file if it exists).
However, it seems that **it instead copies compiled DLL without any exports** into another directory.

And like I already said, this is not the case with UnmanagedExports package; post-build event works fine with UnmanagedExports package, apparently **this bug has been introduced in DllExport code/package**!

To speed things up, you can download my example (DllExport) VS2017 solution from here:
[DllExport-PostBuild-issue.zip](https://github.com/3F/DllExport/files/976889/DllExport-PostBuild-issue.zip)

And here you can also download another example VS2017 solution which uses UnmanagedExports package instead (to see that post-build works correctly with it):
[UnmanagedExports-PostBuild.zip](https://github.com/3F/DllExport/files/976948/UnmanagedExports-PostBuild.zip)

Please fix DllExport :)

**Comment by 3F** [comment]
> I have discovered this bug a while ago and I am surprised to see that it is still not fixed.

Because of different environment, tools, etc. For example, often, I (especially) use vssbe scripts instead of this std. VS Build Events :)

But mainly I have no see any problems as you described for this issue. I mean this:

```
COPY /Y "$(TargetPath)" "$(SolutionDir)$(TargetFileName)"
```

```
TargetPath = <path to file>
TargetFileName = <our file>
SolutionDir = <path to directory>
```

I don't see any wildcards like *.*, *.exp, etc. from your demo projects, and I see expected result for simple command `copy src dest` - a single dll for both cases.

Please check your command, because it can be like this (as I understand for your case):


```bash
xcopy /Y "$(SolutionDir)$(ProjectName)\$(OutputPath)*.*" "$(SolutionDir)"
```

and similar...


since we are talking also about vssbe, same example:

```java
#[IO copy.file("$(ProjectName)\$(OutputPath)*.*", "$(SolutionDir)", true)]
```

or like:

```java
#[$(app = "$(SolutionDir)$(ProjectName)\$(OutputPath)")]
#[IO copy.file({
                    "$(app)*.dll",
                    "$(app)*.exp",
                    "$(app)*.lib"
                }, 
                "$(SolutionDir)", 
                true,
                { "$(app)*.pdb" })]
```

and other


So please review your problem again. And thanks for demo projects, because it always saves my time anyway :)

**Comment by OmegaExtern** [comment]
> I don't see any wildcards like ., *.exp, etc. from your demo projects, and I see expected result for simple command copy src dest - a single dll (without .exp & .lib) for both cases.

I think you have misunderstood the issue here. You though of .exp/.obj generated files? Where did I mention those? Nowhere in above description have I mention anything about exp, obj, or wildcards, vssbe scripts, xcopy, etc. So obviously you misunderstood it, and the point is not to copy ALL files, just the compiled DLL (but that's less important).
The post-build command, in both Visual Studio solutions, if you have build them, then if you compare the destination assemblies of them, you would see that they are not the same, that is:
Destination `UnmanagedExports.dll` **contains DLL exports** (`Method1` exists as expected).
Destination `DllExport.dll` **does NOT contain any DLL exports** (there is no `Method1`).

The main issue is that post-build event is not run at correct time with DllExport package, thus it copied DLL without any exports. Get it?

**Comment by 3F** [comment]
You about **records from IMAGE_DATA_DIRECTORY** :) 
I see, did not noticed because as I said above - it still all ok via vssbe scripts :)

for std. VS build-events I will look later, thanks.

temporarily you can try with vssbe, or try something manually via targets.

**Comment by OmegaExtern** [comment]
Here is the picture to clear it up:
![image](https://cloud.githubusercontent.com/assets/6441892/25776414/c3cfa516-32bd-11e7-98fc-5ef35aab9fa7.png)

**Comment by 3F** [comment]
please check it with latest changes - https://ci.appveyor.com/project/3Fs/dllexport/build/build-45/artifacts

But now we can't use Post-build events (`PostBuildEvent`) before processing our tool. If you need this, use something like:

```xml
<Target Name="PostBuildEventBeforeDllExport" BeforeTargets="DllExportMod">
  <Exec Command="..." ContinueOnError="true" />
</Target>
```
etc.
