### ISSUE TITLE
ILmerge support and other assembly manipulation.

### ISSUE THREAD

**Issue by pabloko** [3F/DllExport#40]
Hello, anyone has ever tried to use ILmerge to combine a lot of resulting assemblies into a compact assembly and transform it to dll library?

Also, any assembly manipulation like code obfuscators fails always.

Its possible to process normally the assemblies then make the build task?

Regards

**Comment by 3F** [comment]
I just looked at this public issue again after answering the latest email-question; Too close :)

Okay, Here's deal:

* About how to use **ILMerge** or ILRepack together with our .NET DllExport 1.7: https://twitter.com/GitHub3F/status/1230164176187936769

* About obfuscators, my today's reply (copy-paste):

> I personally not tested any obfuscators with our DllExport (there was just no need) but for any case we can talk only about POST-processing stage for this tool.
> 
> Means that any 3rd party tool will just destroy our related PE modifications.
> 
> Thus, the only possible way ~ [ Module -> {3rd tool} -> .NET DllExport ]
> ...
> 
> For obfuscators, you only need to try to disable at least attribute modifications when external libraries or even some specific.
> Some obfuscators allows this and it could be very similar to my example with ILMerge above.

**Comment by pabloko** [comment]
hello @3F would you mind to post a link? cant find reference on your tweet. many thanks

**Comment by 3F** [comment]
@pabloko,

o_0 I think this is a correct full url to my tweet that was mentioned earlier:

> https://twitter.com/GitHub3F/status/1230164176187936769

Or what "reference on your tweet" do you mean?

You can also read my complete log with details here: 
* https://ko-fi.com/post/ILMerge-and-other-related-3rd-party-tool-for--NET-Y8Y71FVU4

**Comment by 3F** [comment]
ILMerge is officially supported in our tool, starting with planned 1.7.1:

![Pre-Processing](https://user-images.githubusercontent.com/3246589/80488709-6f4a5280-8967-11ea-83c4-a645e7ef68e6.png)
