### ISSUE TITLE
The install dialog does not accept empty string as a valid namespace and forces namespaces on itself and all dependent packages

### ISSUE THREAD

**Issue by aniongithub** [3F/DllExport#47]
If I have some sort of package hierarchy, it is unreasonable to expect that packages/applications down the chain should use my namespace. If it is undesirable to ship a DLL with this Nuget package that contains this attribute, it should be possible to inject the DllExport attribute into the global namespace if so desired.

Currently

1. The dialog does not accept an empty string as a namespace
2. When given the string "global", it create a literal namespace called "global" (@global) instead of using the global namespace.

Currently the ugly hack I'm having to use is to include a namespace that descendants should not have to know about or care at all. Could this be fixed by simply allowing empty string to represent the global namespace?

**Comment by 3F** [comment]
1. Because I did not implement the global namespace initially :) But ok, why not...
2. **Cecil** can mark this as an special word because https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/global

**However,** you can try this via `Direct-Mod`:

```csharp
global.DllExportAttribute

global::global
global::Microsoft
global::System
...
```
should work

**Comment by 3F** [comment]
It has been implemented in dev_1.6 branch with our new Wizard.
Therefore, you should see this in planned v1.6 soon.
