### ISSUE TITLE
Provided key file ... cannot be found

### ISSUE THREAD

**Issue by dojosan** [3F/DllExport#48]
Hello,

trying to extend a project for unmanaged exports, but when I build the project I get the error:

"Provided key file 'C:\Users\user\documents\visual studio 2017\Projects\ClassLibrary1\ManagedDLL_test\Mono.Cecil.CustomAttributeArgument' cannot be found."

It cannot find the existing snk file or anything else?
Thanks!

**Comment by 3F** [comment]
1. What version and selected configuration ? i.e. IL Assembler, namespace ...
2. Do you use a strong name key `Properties` - `Signing` - `Sign the assembly` ?
3. What version of Visual Studio - `Help` - `About` - `Copy Info` - first 7 lines
4. Can you provide some log of your build:

for details you can set `detailed` or `diagnostics` level:

* VS IDE: `Tools` - `Options` - `Project and Solutions` - `Build and Run` - MSBuild project build verbosity 
* msbuild.exe:  `/v:diag`

**Comment by dojosan** [comment]
Thank you!
Sorry could not answer yesterday. :-(

Here the data:
1. DllExport:
    - version: 1.5.2.22710
    - IL Assembler: on
    - Cecil: on
    - AnyCPU
2.  'Sign the asembly' is not activated! But AsseblyInfo.cs contains the line: "[assembly: AssemblyKeyFile("..\\..\\manageddll_test.snk")]" as it was before intergration of DllExport.
3. Visual Studio:
    - Microsoft Visual Studio Professional 2017 
    - Version 15.2 (26430.16) Release
    - VisualStudio.15.Release/15.2.0+26430.16
    - Microsoft .NET Framework
    - Version 4.6.01590
    - Microsoft Visual Basic 2017
    - Microsoft Visual C# 2017
    - Microsoft Visual C++ 2017
4. Please see the attached log file and also the output data!
Thanks!

[smanageddll_test_log.txt](https://github.com/3F/DllExport/files/1214964/smanageddll_test_log.txt)
[smanageddll_test_out.txt](https://github.com/3F/DllExport/files/1214965/smanageddll_test_out.txt)

**Comment by dojosan** [comment]
Hi,
for now there is no need to look for the reason of the error!
I have just removed the key file line and now I can build the dll!
When I DllExport can create exports I don't need any COM features anyway.
Thanks for being willing to help me!

**Comment by 3F** [comment]
@dojosan thanks for the detailed information

> AsseblyInfo.cs contains the line: "[assembly: AssemblyKeyFile("..\..\manageddll_test.snk")]" as it was before intergration of DllExport.

> I have just removed the key file line and now I can build the dll!

/side note: You can also try to set available `manageddll_test.snk` key file via `Properties` - `Signing` - `Sign the assembly`. Should work.
