### ISSUE TITLE
RPC error using remote debugging in mixed mode with DLLExport?

### ISSUE THREAD

**Issue by michaelplevy** [3F/DllExport#52]
On my local development machine, I can easily use mixed mode debugging and step from my unmanaged console app into my managed .NET Classes that use DLLExport. However, when I try to test on a development server using Visual Studio remote debugging, I can attach and debug in Native mode, but not Mixed mode. In Mixed mode I get the error:

`Unable to start program 'blahblahblah.exe'. The RPC server is unavailable`

For various reasons we are limited to using Visual Studio 2013 (update 5). We are working to upgrade. I did notice this bug report https://connect.microsoft.com/VisualStudio/feedback/details/798692/remote-debugging-with-mixed-mode-fails-on-vs2013-update3 which sounds similar.

Is this a known issue? Is there a work around or any suggestions to get mixed mode remote debugging working?

Thanks.

**Comment by 3F** [comment]
> Is this a known issue?

no, you are first :)

try to disable VS Hosting Process, `Debug` - `Enable the Visual Studio hosting process`:

```xml
<UseVSHostingProcess>false</UseVSHostingProcess>
```

and try to disable this if still:

```xml
<EnableUnmanagedDebugging>false</EnableUnmanagedDebugging>
<EnableSQLServerDebugging>false</EnableSQLServerDebugging>
```

also, the problem may be with mismatched/incorrect/or not loaded pdb data (look this https://github.com/3F/DllExport/issues/23#issuecomment-262805947), or with strong name key files. 
Can you try to reproduce this via new very simple test code to isolate this problem. And first uncheck the generation of .exp & .lib and our asm:

```xml
<DllExportGenExpLib>false</DllExportGenExpLib>
<DllExportOurILAsm>false</DllExportOurILAsm>
```

**Comment by michaelplevy** [comment]
Thank you for the suggestions. We solved our other technical issues and managed to upgrade to VS2017. Now everything seems to work fine. 

So, no more problem here.
