### ISSUE TITLE
Cannot configure solution that contains a .Net Core project

### ISSUE THREAD

**Issue by TheLastRar** [3F/DllExport#56]
### How to reproduce

Create a solution with a .Net Core library
    
### What version and selected configuration ?

v1.6.0b3

### Can you provide detailed log of your build ?

When running DllExport_configure.bat

`[03:11:55 PM.9349] [Fatal] ERROR-Wizard: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\Air\Source\Repos\CLR-DEV9\CLR_DEV9\CLR_DEV9_CORE.csproj`

**Comment by 3F** [comment]
Thanks for the report.

The problem because of new SDK-based format of project files and old MS-logic. 

That is, this part controlled by [MvsSln](https://github.com/3F/MvsSln) project, and this exactly from Microsoft.Build.Evaluation-classes. As I understand, today MS don't want to support many incompatible changes (like this https://github.com/3F/MvsSln/issues/1) at least for .net 4.0...

But, this is not a big problem for DllExport project at least for current features :)

Before fixes, **temporarily** try to use this by adding `xmlns="http://schemas.microsoft.com/developer/msbuild/2003"` attr, for example:

```xml
<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
</Project>
```

**Comment by TheLastRar** [comment]
It now complains about the Remove attribute in element <Compile> being unrecognizable.
Below is the containing item group
```<ItemGroup>
    <Compile Remove="obj_netfx\**" />
    <EmbeddedResource Remove="obj_netfx\**" />
    <None Remove="obj_netfx\**" />
</ItemGroup>```

It also complains about the Version attribute in element <PackageReference>

temporarily removing theses attributes, in addition to your suggestion, allows the configuration tool to run, allowing me to add it to both netfx and netcore projects (although the netcore won't build, complaining that it can't find ildasm.exe (using default IL Assembler)).

**Comment by 3F** [comment]
well yes, because of obsolete schema.

> it can't find ildasm.exe

Can you clarify this part in details ? Currently DllExport still does not support .net core projects if you're trying this. But if you have problem for others, please send detailed build log.

**Comment by TheLastRar** [comment]
This is on a .Net Core project, when attempting to build, there is an error stating it can't find ildasm.exe

The relevant part of the log;

```
1>Target DllExportMod:
1>  Using "DllExportAppDomainIsolatedTask" task from assembly "D:\Air\Source\Repos\CLR-DEV9 - Copy\packages\DllExport.1.6.0-beta3\tools\RGiesecke.DllExport.MSBuild.dll".
1>  Task "DllExportAppDomainIsolatedTask"
1>    Cannot find lib.exe in 'D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\bin'.
1>    D:\Air\Source\Repos\CLR-DEV9 - Copy\packages\DllExport.1.6.0-beta3\tools\net.r_eg.DllExport.targets(56,5): error : Microsoft.Build.Utilities.ToolLocationHelper could not find ildasm.exe.
1>  Done executing task "DllExportAppDomainIsolatedTask" -- FAILED.
1>Done building target "DllExportMod" in project "CLR_DEV9_CORE.csproj" -- FAILED.
```

If you want the full log I can also attach it (it's quite long).

**Comment by 3F** [comment]
yes, please attach the full detailed log as an additional file using the following command:

```
msbuild <YourSlnFile> /t:Rebuild /m:4 /v:diag > build.log
```

**Comment by TheLastRar** [comment]
https://we.tl/LX7hwZTwrk

The Solution has 4 projects
CLR_DEV9 is the main project and is a .netfx project
CLR_DEV9_CORE is the same project, but configured as a .netcore project
DNS Test Thing & UPNP Test Thing are test projects and do not use DllExport (and are both .netfx projects).

The solution file had C++ (Linux) projects, but those where removed to install v1.6.0 (and never readded)

**Comment by 3F** [comment]
Something went wrong with your configuration because I see calling `DllExportMod` for both projects "CLR_DEV9.csproj" & "CLR_DEV9_CORE.csproj" (.NETCoreApp,Version=v2.0)  

```
4>Target "DllExportMod: (TargetId:77)" 
in file "D:\Air\Source\Repos\CLR-DEV9 - Copy\packages\DllExport.1.6.0-beta3\tools\net.r_eg.DllExport.targets" 
from project "D:\Air\Source\Repos\CLR-DEV9 - Copy\CLR_DEV9\CLR_DEV9.csproj" (target "PostBuildEvent" depends on it):
```

```
5>Target "DllExportMod: (TargetId:86)" 
in file "D:\Air\Source\Repos\CLR-DEV9 - Copy\packages\DllExport.1.6.0-beta3\tools\net.r_eg.DllExport.targets" 
from project "D:\Air\Source\Repos\CLR-DEV9 - Copy\CLR_DEV9\CLR_DEV9_CORE.csproj" (target "PostBuildEvent" depends on it):
```

Can you try to reconfigure all this again by removing from all projects, and also choose '.targets file' storage (.net.dllexport.targets). I still can't reproduce this error even if .net core-based project has dependencies to projects with DllExport modification. In addition, you also may reproduce this structure of projects as an simple demo, then attach for debug.

p.s.: please attach anything (including text-based log above) as zip archive etc. still via github attachments.

**Comment by TheLastRar** [comment]
The configuration was intentional, I was wanting to see if DllExport export worked with .Net Core projects (It didn't).

The solution builds correctly if DllExport is removed from CLR_DEV9_CORE and only configured for CLR_DEV9.

I mentioned before that the two projects are effectively the same, CLR_DEV9 is intended for windows users and CLR_DEV9_CORE is the Linux port (hence the need for CoreCLR), the builds are not dependent on each other.

If DllExport does not support .NetCore, then I will have to create a wrapper for the .NetCore version of the project.

**Comment by 3F** [comment]
> The solution builds correctly if DllExport is removed from CLR_DEV9_CORE and only configured for CLR_DEV9.

Good ! as I expected.

And yes, again: we still [have no official support for .net core projects](https://github.com/3F/DllExport/issues/56#issuecomment-344408800).
* **Details**: https://github.com/3F/DllExport/issues/17#issuecomment-335001440

**Comment by 3F** [comment]
@TheLastRar please check the latest changes - [build70](https://ci.appveyor.com/project/3Fs/dllexport/branch/master/artifacts) ( 20eb9db )

![dxpinternalerrormsg](https://user-images.githubusercontent.com/3246589/32950594-e8dd46f4-cbb7-11e7-961e-b7f8afb47eca.png)

**Comment by TheLastRar** [comment]
The new bat file failed with
```
'a4' is not recognized as an internal or external command,
operable program or batch file.
MSBuild tools was not found. Try with `-msb` key. `-help` for details.
```

If i use the old bat file, but keep the files in DllExport.1.6.0-beta3 as build70, the configuration tool launches correctly, detecting the Core and C++ projects as unload-able and allows me to configure the framework project (CLR_DEV9).

I uninstalled and reinstalled DllExport to check if that works and builds (it does).

**Comment by 3F** [comment]
Thanks for the reply ! Seems problem for **LF** from AppVeyor CI


Please check new build71 (same commit) with:
```
git config --global core.autocrlf true
```
https://ci.appveyor.com/project/3Fs/dllexport/build/build-71

**Comment by TheLastRar** [comment]
Yes that version works correctly

**Comment by 3F** [comment]
Good ! v1.6 will be soon. Anyone else, please test latest beta as carefully as possible.
