### ISSUE TITLE
I cannot build it.

### ISSUE THREAD

**Issue by Menjac123** [3F/DllExport#57]
https://i.imgur.com/qW3268b.png

**Comment by 3F** [comment]
I have no problem with current repo. Also fine with latest CI build via AppVeyor:
https://ci.appveyor.com/project/3Fs/dllexport/build/build-71  (yesterday - 20eb9db8 )

Please check yourself, or attach detailed log.

**Comment by Menjac123** [comment]
How can I post a log when everytime CMD is turning off after I'm trying to compile it ?

Can you send me a compiled build please ?

**Comment by 3F** [comment]
:))

```
build > .log
```

if you just need this binaries from CI, see `artifacts` tab:
* https://ci.appveyor.com/project/3Fs/dllexport/build/build-71/artifacts

public releases:

[`DllExport`](https://3f.github.io/DllExport/releases/latest/manager/)` -action Configure` [[?](#how-to-get-dllexport)]

**Please read [How to get DllExport](https://github.com/3F/DllExport#how-to-get-dllexport)** !
