### ISSUE TITLE
Wizard. Incorrect layout for zh_CN Simplified Chinese

### ISSUE THREAD

**Issue by 3F** [3F/DllExport#61]
Mentioned here https://github.com/3F/DllExport/issues/59#issuecomment-347938015

Today I installed zh_CN Simplified Chinese for system:

![win10lang](https://user-images.githubusercontent.com/3246589/34053581-693e39da-e1d8-11e7-80f1-7e6ff2518f40.png)

**However**, I still can't reproduce this:

![win10layout_zh_cn](https://user-images.githubusercontent.com/3246589/34053586-6e6ce50a-e1d8-11e7-8b3e-30289e014f33.png)

chcp:

```
20936	x-cp20936	Simplified Chinese (GB2312); Chinese Simplified (GB2312-80)
50227	x-cp50227	ISO 2022 Simplified Chinese; Chinese Simplified (ISO 2022)
```

I don't have initial zh_CN .iso so it really hard to debug this while I can't see problem.

----
Cc: @Genteure

**Comment by 3F** [comment]
@Genteure Can you send screenshot for this binaries:
https://ci.appveyor.com/project/3Fs/dllexport/build/build-74/artifacts

**Comment by Genteure** [comment]
![image](https://user-images.githubusercontent.com/11240579/34080880-fd32be7e-e37f-11e7-8a9c-2ec56594de6b.png)

**Comment by 3F** [comment]
@Genteure it's old build, should be `RC [ f3fb12d ]` 

please try again with the following command:

[`DllExport`](https://3f.github.io/DllExport/releases/latest/manager/)`-pkg-link https://ci.appveyor.com/api/buildjobs/tftgcu1k8mst533w/artifacts/bin\Release\DllExport.1.6.0-RC.nupkg -action Configure`

**Comment by Genteure** [comment]
![image](https://user-images.githubusercontent.com/11240579/34081160-2df2ca0a-e384-11e7-876e-6233f3fd8fe2.png)
![image](https://user-images.githubusercontent.com/11240579/34081165-32094ee8-e384-11e7-8779-fb9c3c6fd16e.png)
Comparison:
![image](https://user-images.githubusercontent.com/11240579/34081149-fef1b66c-e383-11e7-932c-03c3a0b159dd.png)

**Comment by 3F** [comment]
@Genteure I'm a little bit confused. Is this your changes from the second image, or it f3fb12d ? How about diff patch etc. ?

And please screenshot from this (f3fb12d):

> [`DllExport`](https://3f.github.io/DllExport/releases/latest/manager/)`-pkg-link https://ci.appveyor.com/api/buildjobs/tftgcu1k8mst533w/artifacts/bin\Release\DllExport.1.6.0-RC.nupkg -action Configure`

**Comment by Genteure** [comment]
Command I ran:
```
PS > .\DllExport -version
v1.6.0.39116-RC [ f3fb12d ]
PS > .\DllExport -action Configure -pkg-link "https://ci.appveyor.com/api/buildjobs/tftgcu1k8mst533w/artifacts/bin\Release\DllExport.1.6.0-RC.nupkg"
(then screenshot no.1)
```

Screenshot from VS2017 is from branch "issue61"

Personally, I think little bit offset is OK.
One of my personal project, perfect on Windows10, slightly offset (buttons bigger) on Windows7.

By the way, how can I run Wizard from source code(in Debug mode)?

**Comment by 3F** [comment]
By default, the manager still will use **old received packages** for any new version for specific key like `-pkg-link`. Because it just another build but still same version. Thus you should manually reset/remove this before new trying like for command:

> [`DllExport`](https://3f.github.io/DllExport/releases/latest/manager/)`-pkg-link https://ci.appveyor.com/api/buildjobs/tftgcu1k8mst533w/artifacts/bin\Release\DllExport.1.6.0-RC.nupkg -action Configure`

**or** use another path via related keys for new packages.

The version from header should contains f3fb12d. Also, for checking DllExport tool, you should use `-build-info` **instead of** `-version`: 

```
DllExport -build-info
```

```
    S_REL:              RC
    bSha1:              f3fb12d
    bName:              issue61
```

> By the way, how can I run Wizard from source code(in Debug mode)?

1. Set as StartUp `Wizard` project
2. Start external program: C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
3. Working dir: path to packages\DllExport.1.6.0-RC\tools
4. Commands like:
```
"net.r_eg.DllExport.Wizard.targets" /p:wRootPath="D:\\path\\to\\project" /p:wAction="Configure" /p:wPkgPath=packages/DllExport.1.6.0-RC
```

**Comment by Genteure** [comment]
```
PS > .\DllExport -build-info

    S_NUM:              1.6.0
    S_REV:              39116
    S_NUM_REV:          1.6.0.39116
    S_REL:              RC
    bSha1:              f3fb12d
    bName:              issue61
    bRevc:              93
    Wizard .NET:        v4.0
    Configurator .NET:  v4.0
    Configuration:      PublicRelease
    Platform:           AnyCPU
    cfgname:            Release
    revDeltaBase:       2016/10/12
    revDeltaMin:        1000
    revDeltaMax:        65534

                    :: generated by a vsSolutionBuildEvent v0.12.10.10901
```
![image](https://user-images.githubusercontent.com/11240579/34081676-d7289256-e38b-11e7-84f3-304264e66bcc.png)

**Comment by 3F** [comment]
Good ! looks like GdiCharSet = 0 (ANSI) really helps

check this out:

23e9aaf0

[`DllExport`](https://3f.github.io/DllExport/releases/latest/manager/)`-pkg-link https://ci.appveyor.com/api/buildjobs/i7g7p3j6k30re2q8/artifacts/bin\Release\DllExport.1.6.0-RC.nupkg -action Configure`

https://ci.appveyor.com/project/3Fs/dllexport/build/build-75/artifacts

**Comment by Genteure** [comment]
```
PS > .\DllExport -build-info

    S_NUM:              1.6.0
    S_REV:              41930
    S_NUM_REV:          1.6.0.41930
    S_REL:              RC
    bSha1:              23e9aaf
    bName:              issue61
    bRevc:              94
    Wizard .NET:        v4.0
    Configurator .NET:  v4.0
    Configuration:      PublicRelease
    Platform:           AnyCPU
    cfgname:            Release
    revDeltaBase:       2016/10/12
    revDeltaMin:        1000
    revDeltaMax:        65534

                    :: generated by a vsSolutionBuildEvent v0.12.10.10901
PS > .\DllExport -version
v1.6.0.41930-RC [ 23e9aaf ]
```

![image](https://user-images.githubusercontent.com/11240579/34102569-9a102f66-e424-11e7-9bed-662c2467fdac.png)

**Comment by 3F** [comment]
Thanks, looks fixed now.

Can you also check unicode characters (i.e. fields should contain some your hieroglyphs) for this marked places:

![662c2467fdac](https://user-images.githubusercontent.com/3246589/34165098-6bd63712-e4ec-11e7-9584-b20fad3ab5c3.png)


606a6e71

[`DllExport`](https://3f.github.io/DllExport/releases/latest/manager/)`-pkg-link https://ci.appveyor.com/api/buildjobs/7lqoxijs5bban0ff/artifacts/bin\Release\DllExport.1.6.0-RC.nupkg -action Configure`

**Comment by Genteure** [comment]
```
    S_NUM:              1.6.0
    S_REV:              44649
    S_NUM_REV:          1.6.0.44649
    S_REL:              RC
    bSha1:              606a6e7
    bName:              issue61
    bRevc:              95
    Wizard .NET:        v4.0
    Configurator .NET:  v4.0
    Configuration:      PublicRelease
    Platform:           AnyCPU
    cfgname:            Release
    revDeltaBase:       2016/10/12
    revDeltaMin:        1000
    revDeltaMax:        65534

                    :: generated by a vsSolutionBuildEvent v0.12.10.10901
```
Seems pretty good.
![image](https://user-images.githubusercontent.com/11240579/34165710-fc3352b0-e517-11e7-9fcc-11367390b83c.png)

Found another issue: some useable non-english namespace can't be used by DllExport.
![image](https://user-images.githubusercontent.com/11240579/34166027-cd062174-e518-11e7-8f84-fc01627bf30f.png)

Example:
- 中文解决方案名称 (Chinese)
- あいうえおかきくけこ (Japanese)

Maybe open a new issue? 🤔

**Comment by 3F** [comment]
I squashed this into master. Check this out 2409921:
https://ci.appveyor.com/project/3Fs/dllexport/build/build-77/artifacts

Thanks again !

> Found another issue: some useable non-english namespace can't be used by DllExport.

well :) this is so because when I implemented this feature directly I used rule for null-terminated sequence:
https://github.com/3F/DllExport/blob/master/NSBin/Rmod.cs#L76

**But** I can review this later if someone need unicode characters in namespaces.

By the way, you can also use empty/global namespaces after this - #47

**Comment by 3F** [comment]
@Genteure, by the way, can you also check info form?

latest build:
`DllExport -action Info -force -pkg-link https://github.com/3F/DllExport/releases/download/CI-build-92/DllExport.1.6.0.nupkg`

**Comment by Genteure** [comment]
![image](https://user-images.githubusercontent.com/11240579/43592653-9e06f2a8-96a8-11e8-97f2-8cc2a56c0319.png)

**Comment by 3F** [comment]
Thanks! Try this changes: 

`DllExport -action Info -force -pkg-link https://github.com/3F/DllExport/releases/download/CI-build-93/DllExport.1.6.0.nupkg`

And also check this form via `MsgGuiLevel` variable:

`(set MsgGuiLevel=0) & DllExport -action Configure -force -pkg-link https://github.com/3F/DllExport/releases/download/CI-build-93/DllExport.1.6.0.nupkg`

**Comment by Genteure** [comment]
![image](https://user-images.githubusercontent.com/11240579/43598917-83815382-96b8-11e8-927b-b93eefc10173.png)
![image](https://user-images.githubusercontent.com/11240579/43599070-fb0d63b4-96b8-11e8-8e31-b94c56a78eef.png)

**Comment by 3F** [comment]
@Genteure, Thank you again, the final changes merged into master. /build 95

**Comment by 3F** [comment]
The problem with new 1.7 beta3 layout: https://github.com/3F/DllExport/issues/128#issuecomment-566360606

@theoractice, Does it look correct in beta2 for you? mine here https://twitter.com/GitHub3F/status/1205616579607715840

beta3 for me:

![1.7 beta3](https://user-images.githubusercontent.com/3246589/70994339-0a403f80-20df-11ea-9bf4-9bd89e1604dc.png)

I pushed a very simple fix, please check it via CI build. Command like: 

`DllExport -pkg-link https://ci.appveyor.com/api/buildjobs/2019v5981m3ik7d7/artifacts/bin/Release/DllExport.1.7.0-beta3.nupkg`

offline vesion: https://ci.appveyor.com/api/buildjobs/2019v5981m3ik7d7/artifacts/bin%2FRelease%2Foffline.DllExport.1.7.0.60214-beta3%2B7a190c9.zip

**If still:**

Can anyone with Chinese system send a PR for this case? It is hard to reproduce for me even in VM with installed zh_CN Simplified Chinese.

Our UI almost does not contain any logic, just a specified position for controls.

You need ConfiguratorForm (main container) and ProjectItemControl (leaved 'as is' from 1.6.x as an external controls) https://github.com/3F/DllExport/tree/dev/rel/1.7/Wizard/UI

Thanks!

**Comment by Genteure** [comment]
![image](https://user-images.githubusercontent.com/11240579/71024098-25db3280-213f-11ea-968e-3f947b70f49c.png)

Probably caused by different default font? I'm using en_US as my system language at the moment, is default font decided at install?

```ps
PS E:\> Add-Type -AssemblyName System.Drawing
PS E:\> [System.Drawing.SystemFonts]::DefaultFont

FontFamily       : [FontFamily: Name=SimSun]
Bold             : False
GdiCharSet       : 134
GdiVerticalFont  : False
Italic           : False
Name             : SimSun
OriginalFontName :
Strikeout        : False
Underline        : False
Style            : Regular
Size             : 9
SizeInPoints     : 9
Unit             : Point
Height           : 14
IsSystemFont     : True
SystemFontName   : DefaultFont
```
