### ISSUE TITLE
Microsoft.Build.Utilities.ToolLocationHelper could not find ildasm.exe

### ISSUE THREAD

**Issue by PidoMN** [3F/DllExport#70]
When build get this error: Microsoft.Build.Utilities.ToolLocationHelper could not find ildasm.exe.	ClassLibrary1		

VS:  2017 Community 
Target framework:  .NET Standard 1.1
Using Microsoft.NETCore.Portable.Compatibility (1.0.1)

**Comment by 3F** [comment]
DllExport still does not provide support of the .net core. Thanks for using. Stay in touch.
