### ISSUE TITLE
DllExport.bat MSBuild not found

### ISSUE THREAD

**Issue by Olby2000** [3F/DllExport#72]
Downloaded the DllExport.bat.
Run as an administrator in both PS and CMD as "DllExport -action Configure"
Error message: "MSBuild was not found, try: gnt -msbuild "fullpath" args"
MSBuild.exe exists for v4.0, 14.0, 3.5, 2.0

<a href="https://ibb.co/ffYNpS"><img src="https://preview.ibb.co/ghH43n/msbuild.jpg" alt="msbuild" border="0"></a>

**Please advise, thank you!**

**Comment by 3F** [comment]
Thanks for the report. @Olby2000, can you also provide additional information via `-debug` key:

```bat
DllExport -debug
```

Also, please send me log from the following commands below via [hMSBuild](https://github.com/3F/hMSBuild) (based on this)

* https://github.com/3F/hMSBuild/releases/download/v1.2.2/hMSBuild_minified.bat

```bat
hMSBuild -novswhere -novs -debug
```

```bat
hMSBuild -novswhere -debug
```

**Comment by 3F** [comment]
```
try: gnt -msbuild "fullpath" args
```

seems typo from other project
/TODO

**Comment by Olby2000** [comment]
Hi, thanks for your response. Still no luck. Below is the information your requested.

```
> .\DllExport -debug
[ 8:17:57.02 ] dxpName = 'DllExport'
[ 8:17:57.02 ] dxpVersion = '1.6.0'
[ 8:17:57.04 ] dxpTarget = '"packages\\DllExport.1.6.0\\tools/net.r_eg.DllExport.Wizard.targets"'
[ 8:17:57.05 ] -pkg-link = ''
[ 8:17:57.05 ] -server = 'https://www.nuget.org/api/v2/package/'
[ 8:17:57.06 ] _remoteUrl = 'DllExport/1.6.0'
[ 8:17:57.06 ] ngpath = 'packages\\'
MSBuild was not found, try: gnt -msbuild "fullpath" args
Something went wrong. Try to use another keys.
```

```
> .\hMSBuild -novswhere -novs -debug
[ 8:22:21.09 ] trying via MSBuild tools from .NET Framework - .net 4.0, ...
[ 8:22:21.09 ] checking of version: 4.0
[ 8:22:21.14 ] checking of version: 3.5
[ 8:22:21.19 ] checking of version: 2.0
[ 8:22:21.23 ] msbnetf: unfortunately we didn't find anything.
MSBuild tools was not found. Try to use other settings. Use key `-help` for details.
```

```
> .\hMSBuild -novswhere -debug
[ 8:23:16.68 ] trying via MSBuild tools from Visual Studio - 2015, 2013, ...
[ 8:23:16.69 ] checking of version: 14.0
[ 8:23:16.73 ] checking of version: 12.0
[ 8:23:16.77 ] msbvsold: unfortunately we didn't find anything.
[ 8:23:16.78 ] trying via MSBuild tools from .NET Framework - .net 4.0, ...
[ 8:23:16.78 ] checking of version: 4.0
[ 8:23:16.82 ] checking of version: 3.5
[ 8:23:16.86 ] checking of version: 2.0
[ 8:23:16.90 ] msbnetf: unfortunately we didn't find anything.
MSBuild tools was not found. Try to use other settings. Use key `-help` for details.
```

```
PS C:\managed> .\DllExport -msb "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe" -action Configure
MSBuild was not found, try: gnt -msbuild "fullpath" args
Something went wrong. Try to use another keys.

PS C:\managed> .\DllExport -msb "C:\Windows\Microsoft.NET\Framework64\v4.0.30319" -action Configure
MSBuild was not found, try: gnt -msbuild "fullpath" args
Something went wrong. Try to use another keys.

PS C:\managed> .\DllExport -action Configure -msb "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe"
MSBuild was not found, try: gnt -msbuild "fullpath" args
Something went wrong. Try to use another keys.

PS C:\managed> .\DllExport -action Configure -msb "C:\Windows\Microsoft.NET\Framework64\v4.0.30319"
MSBuild was not found, try: gnt -msbuild "fullpath" args
Something went wrong. Try to use another keys.
```

<a href="https://ibb.co/fYGuM7"><img src="https://preview.ibb.co/etxOES/msbuild_v4_0.jpg" alt="msbuild_v4_0" border="0"></a>

**Comment by 3F** [comment]
weird -_-  Okay, @Olby2000, Can you also check what type of EOL for your copy of DllExport.bat / hMSBuild.bat. Because some strange behaviour should be exactly if it's not CR+LF for all lines. Like this: https://github.com/3F/DllExport/issues/56#issuecomment-345264309


About `-msb` key, seems bug. Because GetNuTool section contains own logic for searching msbuild, and exactly via `-msbuild` key. Need to check this in details. Thanks.


But the main section of DllExport.bat contains own request to HKLM -> 4.0, 3.5, 2.0:

```bat
:bi
call :bf "trying via MSBuild tools from .NET Framework - .net 4.0, ..."
for %%v in (4.0, 3.5, 2.0) do (
call :bj %%v Y & if [!Y!]==[1] exit /B 0
)
call :bf "msbnetf: unfortunately we didn't find anything."
exit /B %an%
```

So please check first CR+LF, and check also scope of your env variables, I mean try to start like this:

```bat
setlocal
call DllExport
endlocal
```

Unlikely, but also try with full uncompressed versions of hMSBuild & DllExport.bat:

* DllExport.bat I added artefact for new CI-builds, and re-runned latest commit: https://ci.appveyor.com/api/buildjobs/83j3d3iy4jdmg25i/artifacts/bin%2FRelease%2FDllExport.bat_full.bat
* https://github.com/3F/hMSBuild/releases/download/v1.2.2/hMSBuild.bat

**Comment by 3F** [comment]
@Olby2000 Unfortunately, but I can't reproduce your problem at all. So I can't even understand why you have this error if you already have correct info where msbuild is placed.

The one of the problems, as I said above, probably can be because of incorrect EOL symbols from your copy of this batch file. 

Please check this out. Try again with latest changes if you still have this problem:

```
DllExport -debug -action Configure -force -pkg-link https://github.com/3F/DllExport/releases/download/CI-build-88/DllExport.1.6.0.nupkg
```

* https://github.com/3F/DllExport/releases/download/CI-build-88/DllExport.bat 
(check **sha1 of this file:** `5AB1785D2D9578504A93875BC28871B0342D2A6E`)

Try also again custom msbuild after solving #74 and `setlocal` regions.

Sample:
```
PS D:\tmp\72> .\DllExport -debug -action Configure -force -pkg-link https://github.com/3F/DllExport/releases/download/CI
-build-88/DllExport.1.6.0.nupkg
[17:02:29.44 ] dxpName = 'DllExport'
[17:02:29.45 ] dxpVersion = '1.6.0'
[17:02:29.47 ] Removing old version 'packages\\DllExport.1.6.0' before continue. '-force' key rule.
[17:02:29.50 ] dxpTarget = '"packages\\DllExport.1.6.0\\tools/net.r_eg.DllExport.Wizard.targets"'
[17:02:29.51 ] -pkg-link = 'https://github.com/3F/DllExport/releases/download/CI-build-88/DllExport.1.6.0.nupkg'
[17:02:29.52 ] -server = 'https://www.nuget.org/api/v2/package/'
[17:02:29.52 ] _remoteUrl = ':../packages\\DllExport.1.6.0'
[17:02:29.53 ] ngpath = 'packages\\'

  GetNuTool v1.6.1.48340_23e6489 - github.com/3F
  =========

Getting `` ... Extracting into "D:\tmp\72\packages\DllExport.1.6.0"
[17:02:37.12 ] -sln-dir = ''
[17:02:37.13 ] -sln-file = ''
[17:02:37.13 ] -metalib = ''
[17:02:37.14 ] -dxp-target = ''
[17:02:37.15 ] wRootPath = D:\tmp\72
[17:02:37.15 ] wAction = Configure
[17:02:37.16 ] trying via MSBuild tools from .NET Framework - .net 4.0, ...
[17:02:37.17 ] checking of version: 4.0
[17:02:37.31 ] found: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
[17:02:37.34 ] Target: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\\MSBuild.exe' "packages\\DllExport.1.6.0\\tools/net.r_eg.DllExport.Wizard.targets"
[5:02:38 PM.7848] [Info] vW: 1.6.0.34361  [ a85c78b ]
[5:02:38 PM.7958] [Debug] SlnDir: 'D:\tmp\72\.\'
[5:02:38 PM.7968] [Debug] SlnFile: ''
[5:02:38 PM.7968] [Debug] PkgPath: 'D:\tmp\72\packages\\DllExport.1.6.0\'
[5:02:38 PM.7978] [Debug] MetaLib: 'tools\raw\lib\net20\DllExport.dll'
[5:02:38 PM.7988] [Debug] MgrArgs: '-debug -action Configure -force -pkg-link https://github.com/3F/DllExport/releases/download/CI-build-88/DllExport.1.6.0.nupkg'
[5:02:38 PM.7998] [Debug] DxpTarget: 'tools\net.r_eg.DllExport.targets'
[5:02:38 PM.7998] [Debug] RootPath: 'D:\tmp\72\'
[5:02:38 PM.8008] [Debug] Storage: 'Default'
[5:02:38 PM.8028] [Debug] StoragePath: '.net.dllexport.targets'
[5:02:38 PM.8038] [Debug] Action: 'Configure'
[5:02:38 PM.8048] [Debug] MsgGuiLevel: '-1'
[5:02:38 PM.8078] [Info] Action: Configure; Storage: Default
```

**Comment by 3F** [comment]
Closed due inactivity.

**Comment by andresud** [comment]
Same problem here... any news on that?

**Comment by andresud** [comment]
D:\webapi\WebAPI>DllExport.bat -action configure
MSBuild tools was not found. Try with `-msb` key. `-help` for details.

D:\webapi\WebAPI>DllExport.bat -msb "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64" -action configure
\Microsoft was unexpected at this time.
D:\webapi\WebAPI>DllExport.bat -msb "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\MSBuild.exe" -action Configure
\Microsoft was unexpected at this time.
D:\webapi\WebAPI>DllExport.bat -msb 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\MSBuild.exe' -action Configure
\Microsoft was unexpected at this time.

D:\webapi\WebAPI>DllExport.bat -msb "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\MSBuild.exe" -action Configure
\Microsoft was unexpected at this time.
D:\webapi\WebAPI>DllExport.bat -msb C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\ -action Configure
\Microsoft was unexpected at this time.

D:\webapi\WebAPI>DllExport.bat -msb "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64" -action Configure
\Microsoft was unexpected at this time.
D:\webapi\WebAPI>

**Comment by 3F** [comment]
@andresud,

just to be sure, what version?

```
DllExport -version
```

And how about `-debug` key for your case? 

```
DllExport -debug -action Configure
```

Also,

> \Microsoft was unexpected at this time.

hmm, it maybe be also because of ` (x86)` in path. I mean, I remember something. But modern versions already contains fixes for this anyway. Can you also try with `\\` and for `/` instead of single `\` separator.

And yes, about your msbuild for netfx. What result for:

```
reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0"
```
