### ISSUE TITLE
Possible incorrect VA for clr.dll when debugging at runtime

### ISSUE THREAD

**Issue by 3F** [3F/DllExport#79]
Reported by @davidsanda, in https://github.com/3F/DllExport/issues/77#issuecomment-403071123

Possible exception:

```
Exception thrown at 0x00007FFAF53A2774 (clr.dll) in server_unittests.exe: 0xC0000005: Access violation reading location 0x0000000000000000
```

* `... happens when calling a base constructor from a derived class.`

**Comment by davidsanda** [comment]
I've taken a look at this in assembly and there is simply an unconditional call to unrecognized region of memory. I'll try to create a minimal project that reproduces it, but it is not that simple.

**Comment by 3F** [comment]
@davidsanda, Please clarify the problem. Some related can be due to some incorrect processing in my custom assembler like this: https://github.com/3F/DllExport/issues/125#issuecomment-561245575

Or something related to incorrect arch/types "requests" in heap. See my explanation through Java/JNA etc. Here or for [Conari](https://github.com/3F/Conari) project.

It also can be due to incorrect instructions in certain official MS versions.

Thus, try to isolate problem via very simple code. Any project-sample would be really useful for quick inspection.

Thanks,
