### ISSUE TITLE
Mimic ordinal counter (start from 1 instead of 0)

### ISSUE THREAD

**Issue by OmegaExtern** [3F/DllExport#8]
I think the title says it all.
Ordinal is not as index, thus it should start counting from 1 rather than 0.
Open any native Windows DLL with `dumpbin /EXPORTS` (or use PE explorer program), and you will notice that **ordinal always starts from 1**.

**Comment by 3F** [comment]
Where you found problems with ordinals ? :)

or you need also the [DllMain features](https://github.com/3F/DllExport/issues/5) (#5) ?

In [Conari](https://github.com/3F/Conari) engine I implemented simplified work with export table of PE data for native [features between C# and C++](https://plus.google.com/101239554716569212042/posts/cicbw3RFrxp) ([binding from any exported functions of libraries](https://plus.google.com/101239554716569212042/posts/eQBGF8cHdE1) etc.):

```
typedef struct _IMAGE_EXPORT_DIRECTORY {
    DWORD   Characteristics;
    DWORD   TimeDateStamp;
    WORD    MajorVersion;
    WORD    MinorVersion;
    DWORD   Name;
    DWORD   Base;
    DWORD   NumberOfFunctions;
    DWORD   NumberOfNames;
    DWORD   AddressOfFunctions;     // RVA from base of image
    DWORD   AddressOfNames;         // RVA from base of image
    DWORD   AddressOfNameOrdinals;  // RVA from base of image
} IMAGE_EXPORT_DIRECTORY, *PIMAGE_EXPORT_DIRECTORY;
```

[![addressofnameordinals](https://cloud.githubusercontent.com/assets/3246589/18306302/d8515d14-74f3-11e6-9060-065119866a23.gif)
](https://msdn.microsoft.com/en-us/library/ms809762.aspx#IMAGE_EXPORT_DIRECTORY)

but important note:

```
DWORD Base
    The starting ordinal number for exported functions. For example, if the file exports functions with ordinal values of 10, 11, and 12, this field contains 10. To obtain the exported ordinal for a function, you need to add this value to the appropriate element of the AddressOfNameOrdinals array. 

 *AddressOfNameOrdinals
    This field is an RVA and points to an array of WORDs. The WORDs are the export ordinals of all the exported functions in this module. However, don't forget to add in the starting ordinal number specified in the Base field.
```

and yes, the DllExport uses native ILasm features - see `.export` directive (v-table, flags, fixups etc. will be generated automatically by the compiler)

```csharp
.export [<ordinal>] as <export_name>
```

read also my short explanation [here](https://github.com/3F/DllExport/issues/5#issuecomment-240697109)

**Comment by OmegaExtern** [comment]
> Where you found problems with ordinals ? :)

Export ordinals are 1-based, it is the common practice.

> and yes, the DllExport uses native ILasm features

Yeah, I know how this works, in fact I have made my own "DllExporter"..

**Comment by 3F** [comment]
> it is the common practice.

and ?

Vasya Pupkin loves start from 5 and hates a common practice at all... and ?

**You need** add 4-bytes value from offset 0x10 to each element of the AddressOfNameOrdinals. 

Read more from Matt Pietrek.

If this value does not match at all ... please, say simply, this is it.

I will check it later.

>  I have made my own "DllExporter"..

ok.
