### ISSUE TITLE
has anybody an example for using github/DllExport in vb.net?

### ISSUE THREAD

**Issue by haller9816** [3F/DllExport#82]
#### Version, configuration, commands:   --> dosn't matter

Hi all,

I like to use DllExport, but I need to work in vb.net. On github pages I only found an example with C#, Denis told me he works only with that and not with VB. So he has no example.
My unmanaged language is the good old FORTRAN. If that's not possible I will use C++

Thanks

Olaf

**Comment by 3F** [comment]
@haller9816,  This is why we need to use **issue tracker:**

```
> to build an interface

I hope we're talking not about COM Interface and so on. As result you will have an exported functions (see related PInvoke docs) in your modified pe-module (lib or exe) for your favorite unmanaged language.

What language is planned to use in unmanaged side? We also have screencasts for C++ & Java.

Mainly, please specify error or some details. And please note, we still have no support of .net core.

> Maybe you know someone who have done this.

exactly on vb.net:
           ^
#30   <<<<
#25   <<<<
```

> So he has no example.

The is not so big different from C# if you know what you do.

So, as I said, please specify error or some steps of what you do.

**Comment by haller9816** [comment]
Hi Denis, hi all,

thank you for your answer.
Looks like I don't know what I'm doing. I'm a newbie in such things. I'm not a programmer. I use programming for technical science.
And attached  to your question: Yes I know, dllexport makes .NET functions available in unmanaged languages like C++ and not changes only values and methods. (I didn't found a COM solution. Is there something like that? It would be enough for me.)

But attached is a screenshot from my VB-project try. I'm using Neural Networks for some simulation. And the Neural Networks DLL is written in VB.NET. I like to use it in another simulation program, for wich I write own unmanaged DLL-functions (in FORTRAN) with a typical interface.

Olaf

![dllexport_visualbasic_try01](https://user-images.githubusercontent.com/42702955/44663799-d20c7d80-aa11-11e8-9d90-8055fd6b4dca.JPG)

**Comment by 3F** [comment]
I see. When I was writing you about "not so big different from C#", I 
thought you are just more familiar with vb.net and not with C#. It was 
important to say this before.

COM solution probably will be more difficult for you and your case.

Okay, I'll try vb.net tomorrow or maybe earlier if someone still does 
not help you before me.

**Comment by haller9816** [comment]
Hi Denis,

no problem about what I not know. I'm realistic :-)
And  I will be happy if you try the vb.net solution.

Thank you.

Olaf

**Comment by 3F** [comment]
Olaf,

I checked this via vb.net, and I still don't see big difference, but here is updated documentation:

* https://github.com/3F/DllExport/wiki/Quick-start#vbnet

And now about your code what I'm seeing...

* Firstly, I don't see our attributes at all. For vb.net you need `<DllExport>` (see updated doc)
* Secondly, you need to use **static** methods. For vb.net it seems named as **Shared**, well you need add this. (again, see updated doc).

That is, try this:

```vbnet
<DllExport>
Public Shared Function Netz(...
```

if you need __stdcall:

```vbnet
<DllExport(CallingConvention.StdCall)>
Public Shared Function Netz(...
```

Here also about control missing records in export: https://github.com/3F/DllExport/wiki/Export

Write here if still.

**Comment by haller9816** [comment]
thank you Denis,

but I tried the first version before and now the second version and I got now two errors:
- CallingConvention is not declared
- DllExport is not defined

I did Apply (in different configuration) again: 
![grafik](https://user-images.githubusercontent.com/42702955/44682042-93db8200-aa42-11e8-812f-a64348fab29a.png)


![grafik](https://user-images.githubusercontent.com/42702955/44681684-97bad480-aa41-11e8-89e2-47878c1df4ea.png)

Greetings

Olaf

**Comment by Genteure** [comment]
You need to import the necessary namespace.
A quick and easy way to do that:

- Hover mouse on `DllImport` or `CallingConvention`
- Click on the tooltip icon
- Click import

Or you can just add `Import System.Runtime.InteropServices` at the top.

https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/imports-statement-net-namespace-and-type

**Comment by haller9816** [comment]
thank you, 
"Import System.Runtime.InteropServices" has to be called "Imports System.Runtime.InteropServices"
Than I get no Error.

**Comment by haller9816** [comment]
thank you Denis

**Comment by 3F** [comment]
I am glad that we helped you, Olaf!
