### ISSUE TITLE
ERROR MSB4062 Task could not be loaded

### ISSUE THREAD

**Issue by kevinkouketsu** [3F/DllExport#95]
### How to reproduce
I don't know exactly. I'm just trying to create compile a simple program.

#### Version, configuration, commands:

Versions: 
1.2.7 lastest stable

Configuration:
Project test, debug x86, .NET Any version

#### Project files, samples:
Just a empty project with a .cs. I've added the lib with nuget and compile. 

### log

error MSB4062: The "RGiesecke.DllExport.MSBuild.DllExportAppDomainIsolatedTask" task could not be loaded from the assembly C:\Users\path\source\repos\WpfControlLibrary1\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.MSBuild.dll. Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. O sistema não pode encontrar o arquivo especificado. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

I used the same lib on another computer and just work fine.

-----------

**Comment by 3F** [comment]
Your package does not related to this project. *We are here: https://www.nuget.org/packages/DllExport/*
* Please use **⇝ [ [this](https://3f.github.io/DllExport/releases/latest/manager/) ] ⇜** instead 
[[? wiki](https://github.com/3F/DllExport/wiki/Quick-start)]
